### ISSUE TITLE
Guardian.Plug.EnsureNotAuthenticated

### ISSUE THREAD

**Issue by victorlcampos** [ueberauth/guardian#106]
Hi,
I'm coding a login/sign up views that I have guarantee that the user are not Authenticated, if it is, I have to do something(handler).

Could I code this plug and submit a pull request?

**Comment by doomspork** [comment]
I'm :+1: this but let's see what @hassox thinks.

**Comment by hassox** [comment]
Good idea. This seems like a great add. What would you do in the case where someone is logged in?

**Comment by victorlcampos** [comment]
Call a handler ?

**Comment by doomspork** [comment]
I imagine it would work just like `Guardian.Plug.EnsureAuthenticated` only the handler function would be something like `authenticated/2`.

```elixir
# some_controller.ex
alias Guardian.Plug.EnsureNotAuthenticated
plug EnsureNotAuthenticated, [handler: MyApp.MyAuthErrorHandler] when action in [:signin, :signup]

# my_auth_error_handler.ex
defmodule MyApp.MyAuthErrorHandler  do
  def unauthenticated(conn, _params) do
  end

  def authenticated(conn, _params) do
  end
end
```

**Comment by victorlcampos** [comment]
exactly

**Comment by hassox** [comment]
:+1: sounds good. are you comfortable putting up a PR @victorlcampos?

**Comment by victorlcampos** [comment]
I will try, tomorrow, are you ok with this date?

**Comment by doomspork** [comment]
Sounds good @victorlcampos :+1:

**Comment by victorlcampos** [comment]
@doomspork and @hassox PR opened #109

**Comment by hassox** [comment]
This has been merged. Thanks @victorlcampos!

**Comment by victorlcampos** [comment]
Thank you for this anwsome lib
