### ISSUE TITLE
PR Proposal: Guardian Generators

### ISSUE THREAD

**Issue by victorlcampos** [ueberauth/guardian#107]
Hi guys,
I realy like guardians, but a devise's feature that i miss is the generators. Because of this I startad create it:

https://github.com/victorlcampos/gen_guardian

What do you think? Could I open a pull request to guardian project to add this to it?

**Comment by aristotelesbr2014** [comment]
Nice! +1

**Comment by hassox** [comment]
I love the idea of generators, but I think of guardian as a core style lib. I don't think it's appropriate to guide people in a particular direction in the core lib, but stoked to see that generators are being built on top of it. I think (at least in the near term) that a separate repo like gen guardian is great to have.

**Comment by victorlcampos** [comment]
Thx for reply. I happy you by stoked =)
If you have some sugest to generators?

Next weekend I will try to write some tests

**Comment by hassox** [comment]
I think sentinel is doing something similar. You might want to pool your time with them (or not)

https://github.com/britton-jb/sentinel

**Comment by victorlcampos** [comment]
Thx @hassox, Yes, I will send PR

**Comment by victorlcampos** [comment]
https://github.com/britton-jb/sentinel/issues/1
