### ISSUE TITLE
Storing Guardian permissions in the User record?

### ISSUE THREAD

**Issue by neezer** [ueberauth/guardian#119]
Hi, I'm new to Elixir/Phoenix/Guardian, but I've gotten an API up and running with Guardian configured. Presently, I'm hard-coding permissions for all my users like so:

```elixir
{ :ok, jwt, full_claims } = Guardian.encode_and_sign(user, :token, %{
  name: user.name,
  perms: %{ admin: [:dashboard] }
})
```

But I was wondering how I might save the [permissions bit](https://github.com/ueberauth/guardian#permissions) on my user record, so that different users could have different permissions (and thus get different tokens).

How might I do this?

**Comment by neezer** [comment]
Apologies, now that I've played around with this some more, I realize it's not a Guardian specific question. Came up with the below solution.

---

I added a `map` to my user record... and defaulted it to `%{}`. Since I'm using PostgreSQL, I have the field type set to `:json`.

```elixir
defmodule Mpapi.User do
  schema "users" do
    field :permissions, :map
    # ...
  end
  # ...
end
```

Then I can save my permissions per-user by passing in the same declaration I was using to generate the token previously:

```elixir
Repo.update!(User.changeset(user, %{ permissions: %{ default: [:read, :write] }})
```

Finally, when I'm creating the token, I now do this:

```elixir
{ :ok, jwt, full_claims } = Guardian.encode_and_sign(user, :token, %{
  name: user.name,
  perms: user.permissions
})
```

**Comment by nathanbuchar** [comment]
This was very helpful, thank you for outlining your solution :)
