### ISSUE TITLE
Why does EnsurePermissions require key?

### ISSUE THREAD

**Issue by wende** [ueberauth/guardian#126]
I'm developing with Guardian right now, and I want a part of a website to be available to both `default` user and `admin`
Because of that I distributed the permissions like that
```elixir
permisions: %{
  default: [
    :see_page
  ],
  admin: [
    :see_page,
    :do_admin_stuff
   ]
}
```
But right now if I want to check the permissions using plug I'm unable to check the permission by name
because 
```elixir
plug EnsurePermissions, [handler: __MODULE__, default: [:see_page]]
```
Which still doesn't allow the admin to see the page, because it check under a key instead of checking the permission itself
Did I get something wrong or is the permissions model quite unintuitive?

**Comment by doomspork** [comment]
@wende it shouldn't be necessary to copy `default` into `admin`, you can assign both permissions to a user.  To work with your original plug, this is what I might do:

```elixir
defp user_claims(%User{admin: true}) do
  %{default: [:see_page], admin: [:do_admin_stuff]}
end
defp user_claims(_) do
  %{default: [:see_page]}
end

Plug.sign_in(user, :token, perms: user_claims(user))
```

As to why we need the key?  It allows for granular permissions.  You probably don't want `users` accessing your admin panel so you could do something like this:

```elixir
plug EnsurePermissions, [handler: __MODULE__, admin: [:see_page]]
```

Does that help?

**Comment by ashrafhasson** [comment]
I'm facing a similar issue where normal user should have "update_self" permission and admin user should have "update" permission both of which apply to the same action, with @doomspork 's setup it still doesn't authorize the request when tested. Only the specific profile gets allowed, so if I specify "admin", a user with signed with %{default: ~w(update)} will not be able to request that path.

**Comment by hassox** [comment]
The `key

**Comment by hassox** [comment]
If there's nothing else required on this one I'm going to close it out. Please re-open if there's more you need.
