### ISSUE TITLE
Definition of location not present in README.md

### ISSUE THREAD

**Issue by martinos** [ueberauth/guardian#130]
I try to understand what is a `location` but I can't figure it out from the README.  It would be clearer if it is explained in the docs.

**Comment by doomspork** [comment]
@martinos would you mind taking a shot at expanding on the documentation?

**Comment by martinos** [comment]
At many place in the `README.md` file they talk about a `location`.

Example:

```
Guardian.Plug.claims(conn) # Access the claims in the default location
Guardian.Plug.claims(conn, :secret) # Access the claims in the secret location
```
What does it mean ? Is it where claims is stored ? It's not clear to me.   

I would gladly write some documentation about it, however I don't understand what it is.

**Comment by hassox** [comment]
When the README talks about 'locations' it's talking about:

a. Where guardian will look for the token in the session
b. Where it will store it in the connection

This allows you to have multiple logins on the same connection for purposes like impersonation or 'more secure' logins at the same time as your normal login.

For example:

`Guardian.Plug.claims(conn)` will fetch the claims from the conn in `guardian_default_claims` while `Guardian.Plug.claims(conn, :secret)` will fetch the claims from conn in `guardian_secret_claims`. 

This is just a mechanism to allow multiple token/claims/resource on the one connection simultaneously. 

Does that make sense?

**Comment by martinos** [comment]
Thanks for the explanation, I think I understand. Am I right if I say that the `location` is the key where the claim is stored in the session ?

**Comment by hassox** [comment]
Pretty much. Both in the session, and on the conn object.
