### ISSUE TITLE
Upgrading Guardian

### ISSUE THREAD

**Issue by nathany** [ueberauth/guardian#141]
Upgrading guardian from 0.9.1 to 0.10.1 and guardian_db to 0.4.0 to 0.5.0 is resulting in this error:

```
== Compilation error on file web/channels/authorized_channel.ex ==
** (CompileError) web/channels/authorized_channel.ex:3: undefined function params/0
```

Line 3 is:

```elixir
use Guardian.Channel
```

elixir 1.2.4
ecto 2.0 rc.1

**Comment by bsidoruk** [comment]
It seems to be here, https://github.com/ueberauth/guardian/blob/master/lib/guardian/channel.ex#L46

**Comment by hassox** [comment]
Thanks for the bug report!

**Comment by doomspork** [comment]
Fixed thanks to @danielfarrell 👍

**Comment by nathany** [comment]
Thanks!
