### ISSUE TITLE
Remember password

### ISSUE THREAD

**Issue by martinos** [ueberauth/guardian#142]
I am trying to add a remember password feature to my app, however it seems that the jwt is stored in the session in a temporary manner. 

Is it possible with the current state of guardian to implement this feature in an app ? If not, is there a plan to add this feature in guardian ?

**Comment by hassox** [comment]
It is possible. The approach I'd use is to store a specific type of token with a long ttl that can't be used elsewhere (think refresh token). Then write a plug to look this up and create a new access token for the session. 

```elixir
{:ok, token, claims } = Guardian.encode_and_sign(user, :remember)
conn = Plug.put_resp_cookie("remember_me", token)
...
```

That's on the way out. On the way in, check your session first with Guardian.Plug.VerifySession, then use a different plug that if verify session resulted in a session being loaded does nothing, but if not, check the `remember_me` cookie for a token and create a new token based on it for the session.

Does that make sense?

**Comment by martinos** [comment]
Makes a lot of sense, thanks for your response. I have never thought of storing the JWT in a different cookie that the session's one. 

I'll try it this next week-end.

**Comment by mitkins** [comment]
I'm having trouble implementing the part where the new token is stored in the session and the page continues without redirect. Here's the crux of my current implementation:

    jwt = conn.req_cookies["remember_me"]

    case Guardian.decode_and_verify(jwt) do
      { :ok, claims } ->
        if ( claims |> Map.get("typ") == "remember" ) do
          { :ok, remember_user } = load_resource( conn, claims, opts )

          # This doesn't seem to do what I want
          conn |> Guardian.Plug.sign_in( remember_user )
        end

      { :error, reason } ->
        # Do something
    end

I have this in a Plug that runs after `LoadResource`. Although the code runs, it does not change the outcome. The page still redirects after `EnsureAuthenticated`

Full details are in this [SO question](http://stackoverflow.com/questions/39715722/guardian-remember-me-using-refresh-token).

Am I on the right track?
