### ISSUE TITLE
Guardian.Plug.claims does not return a map

### ISSUE THREAD

**Issue by simonh1000** [ueberauth/guardian#146]
I followed http://blog.overstuffedgorilla.com/simple-guardian-api-authentication/ and ran into an exception with 
```
claims = Guardian.Plug.claims(new_conn)
exp = Map.get(claims, "exp")
```
 ** (BadMapError) expected a map, got: {:ok, %{"aud" => "User:2", "exp" => 1464245528, "iat" => 1461653528, "iss" => "JwtExample", "jti" => "302c925b-f978-4734-9a15-853bb96d0faf", "pem" => %{}, "sub" => "User:2", "typ" => "token"}}
        (stdlib) :maps.find("exp", {:ok, %{"aud" => "User:2", "exp" => 1464245528, "iat" => 1461653528, "iss" => "JwtExample", "jti" => "302c925b-f978-4734-9a15-853bb96d0faf", "pem" => %{}, "sub" => "User:2", "typ" => "token"}})

Looks as though Guardian.Plug.claims is wrapping the claims as `{:ok, claims}`

**Comment by leandroalemao** [comment]
@simonh1000 I'm still learning and playing with Phoenix.. but I think you should do.. shouldn't you?

`{:ok, claims} = Guardian.Plug.claims(new_conn)`

**Comment by hassox** [comment]
Correct it's a tuple. The reason is that when decoding the token we can have an error.
