### ISSUE TITLE
Use Guardian with two separate configurations in the same application

### ISSUE THREAD

**Issue by jaybrueder** [ueberauth/guardian#156]
I am looking into Guardian right now and want to know if it is possible to have two separate Guardian configurations in one Phoenix application. 

I want to have a User and an Admin model. The User tokens should be valid for 30 days and the admin tokens only for 1 day. Also, I want to have a separate `secret_key` for each model.

Currently, I can only solve this by adding an `:admin` permission to the User token. However, the token will still have a validity of 30 days and not 1. Also, the secret would be the same.

Maybe like this:

```
config :guardian, Guardian,
  allowed_algos: ["HS512"],
  verify_module: Guardian.JWT,
  issuer: "Jay",
  ttl: { 30, :days },
  verify_issuer: true,
  secret_key: "<super-secret-key>"

# Have a separate config für Admin model
config :guardian_admin, Guardian,
  allowed_algos: ["HS512"],
  verify_module: Guardian.JWT,
  issuer: "Jay - Admins",
  ttl: { 1, :days },
  verify_issuer: true,
  secret_key: "<-admin-super-secret-key>"
``` 

Is there a way to use Guardian with two separate configurations in the same application?

**Comment by hassox** [comment]
Unfortunately you can't have two configurations for guardian at the moment. However you can manually specify the secrets in the calls to `encode_and_sign` and `decode_and_verify`. The same goes for the ttl settings.

**Comment by hassox** [comment]
I think this could be a great addition but would be a pretty hefty breaking change :\

**Comment by doomspork** [comment]
Closing this for the time being.  If this comes back up we can create a new issue for the enhancement.
