### ISSUE TITLE
Ability to verify permissions to join channel

### ISSUE THREAD

**Issue by chvanikoff** [ueberauth/guardian#158]
As of now, there's no such functionality built-in but I think it may be useful for more people than just me.
Simple use case - administrator channel where only users with `%{"pem" => %{"admin" => 1}}` can join.
Currently I'm doing
```elixir
def join("admin", _params, socket) do
  %{"pem" => pem} = current_claims(socket)
  case pem do
    %{"admin" => 1} ->
      {:ok, %{message: "Joined"}, authed_socket}
    _ ->
      {:error, :authentication_required}
  end
  {:ok, socket}
end
```
but I'd prefer to have this out of the box and be able to use it just like EnsurePermissions plug by providing required access level to somewhere.

**Comment by hassox** [comment]
I wouldn't try to use the bitmask directly. `Guardian.Permissions.all?/2` is likely what you're after here.

```elixir
can_access? = socket
|> current_claims()
|> Guardian.Permissions.from_claims(:admin)
|> Guardian.Permissions.all?([:your_permission_name], :admin)
```
