### ISSUE TITLE
Doubt: How to deny access to all pages with Guardian.

### ISSUE THREAD

**Issue by nubunto** [ueberauth/guardian#159]
How to make sure there is no way to access pages if someone isn't authenticated?

**Comment by hassox** [comment]
Hi. Can you please use some more words. The `Guardian.Plug.EnsureAuthenticated` plug is probably what you want but without anything to go on I can't really be sure ;)

**Comment by nubunto** [comment]
Sorry.

Actually what I meant was how to show a page to everyone who isn't authenticated.
But I managed to solve it anyway.

Thanks and sorry again!
