### ISSUE TITLE
Use Guardian without Model

### ISSUE THREAD

**Issue by srh-work** [ueberauth/guardian#163]
Hello,

I want to know if it is possible to use Guardian without a user model and how to use it.
I use Phoenix just for server, tiny api and channels. I have a database in the browser with PouchDB and I want to authorized access to the tiny api. The thing is I don't have and I don't want to have models in my backend, but Guardian need a resource for serialize the token.

Is possible to do something in this scenario?

When I call the method `Guardian.serializer.for_token(user)` or  `Guardian.encode_and_sign(:token)` (with user a map) the return is `Unknown resource type`.

My `guardian_serializer.ex` is:
```elixir
@behaviour Guardian.Serializer

def for_token(user = %{:id => 88888888}), do: {:ok, "User:#{user.id}"}
def for_token(_), do: {:error, "Unknown resource type"}

def from_token("User:" <> id), do: {:ok, "User:#{id}"}
def from_token(_), do: {:error, "Unknown resource type"}
```

Thanks.

**Comment by hassox** [comment]
I use Guardian without a model many times when I just want to know that someone is authenticated but without providing a mapping to the resource that is authenticated. There's nothing stopping you from putting just a straight up string or integer in that place. For example:

```elixir
@behaviour Guardian.Serializer

def for_token(id), do: {:ok, id}

def from_token(id), do: {:ok, id}
```

You could then generate your token like this:

```elixir
Guardian.encode_and_sign(15, :access)
```

The serializer in this case will just pass through whatever you pass through both on serialize and deserialize and the integer 15 will be stored in the 'sub' field of your token.

**Comment by doomspork** [comment]
@srh-work can we close this issue?
