### ISSUE TITLE
Erlang debugger cannot inspect Guardian module

### ISSUE THREAD

**Issue by christiansakai** [ueberauth/guardian#179]
I'm following this example to start Erlang debugger http://blog.plataformatec.com.br/2016/04/debugging-techniques-in-elixir-lang/

I noticed that other modules such as `Guardian.Plug.VerifyHeader` and `Guardian.Plug.LoadResource` can be inspected just fine but not the `Guardian` itself.

```
:debugger.start()
:int.ni(Guardian) # throw errors
```

**Comment by doomspork** [comment]
Thanks for bringing this to our attention @christiansakai.  I personally don't have much experience with the debugger so maybe @hassox or @scrogson can chime in.

If not, I'd be happy to take a peek at this later in the week.

**Comment by doomspork** [comment]
@christiansakai is this still an issue for you?

**Comment by christiansakai** [comment]
@doomspork not really, I figured out how to use Guardian with just printing out stuff to inspect. In terms of whether the erlang debugger still not able to inspect Guardian, yes.
