### ISSUE TITLE
Passing params to connect is deprecated. Instead pass :params to the Socket constructor

### ISSUE THREAD

**Issue by douglascorrea** [ueberauth/guardian#184]
I'm using Guardian to authenticate my channels and I'm using it on socket.connect.

But I saw that the javascript console shows a message that passing parameters in connect is deprecated.

If I try to use :params in the socket constructor the out-of-box Guardian.Phoenix.Socket do not work.

Is there something I'm missing here or is it need a change in guardian to support passing parameters in Socket constructors?

**Comment by doomspork** [comment]
@douglascorrea there may have been a chance to Phoenix Sockets that warrants a Guardian change, do you have a project we could look at that demonstrates this error?

**Comment by douglascorrea** [comment]
@doomspork sorry about late answer I will setup a project to reproduce and ping you here.

**Comment by doomspork** [comment]
@douglascorrea any updates or can I close this ticket?

**Comment by douglascorrea** [comment]
Hi @doomspork sorry, I really forgot this. Please go ahead and close it, as soon I get time to create a project to reproduce it I ping this issue and we re-open it if necessary.
