### ISSUE TITLE
Using a function in config causes exrm releases to fail

### ISSUE THREAD

**Issue by peuh** [ueberauth/guardian#187]
According to the doc, one can do:

```elixir
## %JOSE.JWK{} Struct ##
# Useful if you store your secret key in an encrypted JSON file with the passphrase in an environment variable.

config :guardian, Guardian,
  allowed_algos: ["Ed25519"],
  secret_key: fn ->
    System.get_env("SECRET_KEY_PASSPHRASE") |> JOSE.JWK.from_file(System.get_env("SECRET_KEY_FILE"))
  end
```

When importing the key this way, the generation of releases will fail with the following message:

`Cannot add file sys.config to tar file - [{error,{16,erl_parse,["syntax error before: ",["Fun"]]}}]`

The sys.config line causing the issue is:

`{secret_key,#Fun<erl_eval.20.50752066>}]}]},`

So in scenario where the JWK must be loaded from a pem file, it might be preferable to do it from the application `start/2`:

```elixir
 guardian_env = Application.get_env(:guardian, Guardian)
 new_guardian_env = guardian_env |> Keyword.put(:secret_key, JOSE.JWK.from_pem_file( Keyword.get(guardian_env, :secret_key_path)))
 Application.put_env(:guardian, Guardian, new_guardian_env)
```

Also, maybe the guardian could handle this `secret_key_path` out of the box for people who'd rather have the path to the pem file in the config rather than in an env var.

**Comment by doomspork** [comment]
Howdy @peuh!  Thanks for taking the time to report this.   Would you be open to implementing this functionality and updating the README?

**Comment by peuh** [comment]
I can give it a try but I'm afraid I won't have time before the end of next week. Also, I've only been using elixir for a month, so my PR might be a bit rough around the edge and need some polishing. Would it work for you?

**Comment by doomspork** [comment]
@peuh that's okay!  We're more than happy to help with feedback.

**Comment by SLOBYYYY** [comment]
I have the same issue. IMO this issue is related to `release` task than to guardian since `release` creates the sys.config file and therefore fails (due to negligence or on purpose) to evaluate the function in config.exs.

I was trying it with `exrm`, did not have time to take a shot at [https://github.com/bitwalker/distillery](https://github.com/bitwalker/distillery) (this is the official successor of `exrm`)

What plugin do you use for release?

**Comment by doomspork** [comment]
@SLOBYYYY interesting point, have you raised this issue over at `exrm` or `distillery`?

**Comment by SLOBYYYY** [comment]
As you can see I did. You can close this since it comes up with all anonymous functions when you use a release plugin (`exrm` or `distillery`)

**Comment by doomspork** [comment]
Thank you @SLOBYYYY!!
