### ISSUE TITLE
no function clause matching in Guardian.jose_jwk/1

### ISSUE THREAD

**Issue by hollow** [ueberauth/guardian#190]
Hi,

I've tried to get guardian up and running, initially following the tutorial at https://medium.com/peep-stack/building-a-performant-real-time-web-app-with-ember-fastboot-and-phoenix-part-2-5dd2f74c7f34#.xv7exan03

Meanwhile I have tried a lot of different things, read through the readme a couple of times, but no matter what i try, I always get the following error from guardian:

```
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Guardian.jose_jwk/1
        lib/guardian.ex:292: Guardian.jose_jwk('UcaZRz3eJdHfzhMvOVsLnuP5V3zlfs1pvJcdCJWo4+Ay0/TkFkgkQfzottcBOoXj')
        lib/guardian.ex:302: Guardian.encode_claims/1
        lib/guardian.ex:94: Guardian.encode_from_hooked/1
        lib/guardian/plug.ex:179: Guardian.Plug.api_sign_in/4
        (api) web/controllers/session_controller.ex:21: Api.SessionController.login/2
```

Am I missing something or is this a bug?

**Comment by keithalpichi** [comment]
@hollow What does your session controller look like? Mind posting it?

**Comment by hollow** [comment]
@keithalpichi the controller is just a copy of https://gist.github.com/mike-north/efb910d4eca4909fe0dcbc054bc6043e#file-session_controller-ex with `Peepchat` replaced by `Api`. the stack trace above does not match 100% since I've played aroun with using `api_sign_in` and other methods, but the error is always the same in jose_jwk.

FWIW I've switched to auth0 and Joken for verification meanwhile ...

**Comment by hassox** [comment]
@hollow it seems like you might be missing a secret in your configuration

**Comment by AbdullahDahmash** [comment]
I had this problem I believe you followed the tutorial like this
```elixir
config :guardian, Guardian,
  allowed_algos: ["HS512"], # optional
  verify_module: Guardian.JWT,  # optional
  issuer: "Peepchat",
  ttl: { 30, :days },
  verify_issuer: true, # optional
  secret_key: System.get_env("GUARDIAN_SECRET") || "anUG...A4qfP5",
  serializer: Peepchat.GuardianSerializer
```

I don't know why but this is producing some problems.
You need to separate it. In dev.exs and test.exs, type the dev secret key as following
```elixir
config :guardian, Guardian,
  allowed_algos: ["HS512"], # optional
  verify_module: Guardian.JWT,  # optional
  issuer: "Peepchat",
  ttl: { 30, :days },
  verify_issuer: true, # optional
  secret_key: "anUG...A4qfP5",
  serializer: Peepchat.GuardianSerializer
```

in prod.exs, use the system environment 
```elixir
config :guardian, Guardian,
  allowed_algos: ["HS512"], # optional
  verify_module: Guardian.JWT,  # optional
  issuer: "Peepchat",
  ttl: { 30, :days },
  verify_issuer: true, # optional
  secret_key: System.get_env("GUARDIAN_SECRET"),
  serializer: Peepchat.GuardianSerializer
```
