### ISSUE TITLE
Check if a user is authenticated

### ISSUE THREAD

**Issue by GildedHonour** [ueberauth/guardian#191]
After a user signed in:
```
def create(conn, params = %{}) do
    conn
    |> put_flash(:info, "Logged in.")
    |> Guardian.Plug.sign_in(verified_user) # verify your logged in resource
    |> redirect(to: user_path(conn, :index))
  end
```

how do I check on if they are authenticated in other places? Say,  a page "users/secret_page"  is avaialble only for authenticated users. When a user comes to that page, how do I check if they're authenticated?

**Comment by migore** [comment]
O just found this, it helped me. Hope it helps.
https://hexdocs.pm/guardian/Guardian.Plug.html#authenticated?/1

**Comment by doomspork** [comment]
Hi @GildedHonour, have you looked at `Guardian.Plug.EnsureAuthenticated`? 

https://github.com/ueberauth/guardian#guardianplugensureauthenticated

**Comment by GildedHonour** [comment]
Thanks. It doesn't support confirmations, user password recovering, email confirmation, locking users and so on?

**Comment by doomspork** [comment]
@GildedHonour that functionality isn't provided by Guardian.  If you're familiar with the Ruby ecosystem Guardian is akin to Warden upon which Devise (and others) are built.

**Comment by GildedHonour** [comment]
@doomspork what do you recommend to use as alternive of devise gem from Rails?

**Comment by doomspork** [comment]
@GildedHonour as far I as know no one has built something like Devise for Elixir.  For my use-cases I roll my own functionality.

**Comment by GildedHonour** [comment]
Thanks.
