### ISSUE TITLE
Cannot seem to attach permissions to JWT token

### ISSUE THREAD

**Issue by jaybrueder** [ueberauth/guardian#193]
Hi,

I have the following problem:

I want to include permissions inside my JWT token so that I can check for them later with `Guardian.Plug.EnsureAuthenticated`.

This is how my code looks:
# config.exs

```
config :guardian, Guardian,
  allowed_algos: ["HS512"],
  verify_module: Guardian.JWT,
  issuer: "Docin",
  ttl: { 30, :days },
  verify_issuer: true,
  secret_key: System.get_env("GUARDIAN_SECRET") || "xB/riG0....",
  serializer: DocinApi.GuardianSerializer,
  permissions: %{
    admin: [
      :all
    ],
  }
```
# The controller that creates the JWT:

```
claims = Guardian.Claims.app_claims
         |> Map.put(:perms, %{ admin: [:all] })

# Encode JWT
{ :ok, jwt, full_claims} = Guardian.encode_and_sign(user, :token, claims)

conn
|> json(%{access_token: jwt})
```
# My routes

```
pipeline :admins do
    plug :accepts, ["json"]

    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
    plug Guardian.Plug.EnsureAuthenticated, handler: MyApp.AuthErrorHandler, admin: [:all]
end

scope "/api/admins/", MyApp do
    pipe_through :admins

    get "/current", AdminController, :current
end
```

So the idea would be that without the `admin: [:all]` permissions you would not be allowed to access any route inside the `/api/admins/` scope at all. 

Without using a token, it works as expected: `401: Unauthorized` 

If I configure the `Guardian.Plug.EnsureAuthenticated` like above, I get an `401: Unauthorized` error even **when using the token**. 

If I remove the `admin: [:all]` form it, it works just fine with the token.

So I guess the permissions are not inside the token?

This is the request I would send to access the `/api/admins/current` route:

```
GET /api/admins/current HTTP/1.1
Host: localhost:4000
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzUxMiIsIn... (token shortened)
Cache-Control: no-cache
Postman-Token: d00116fb-1b41-9be4-2aaf-646fb54234db
```

Anyone of you had this problem before? 

I would appreciate any help :)

**Comment by doomspork** [comment]
@jaybrueder you should be using `Guardian.Plug.EnsurePermissions` to check permissions.  It sounds like there may be something misconfigured with your application with regards to how `Guardian.Plug.EnsureAuthenticated` is working.

Do you have an example project we could look at?

**Comment by hassox** [comment]
@doomspork is correct. EnsurePermissions is what you want here. Also just a quick comment on the code you posted.

```
claims = Guardian.Claims.app_claims
         |> Map.put(:perms, %{ admin: [:all] })

# Encode JWT
{ :ok, jwt, full_claims} = Guardian.encode_and_sign(user, :token, claims)

conn
|> json(%{access_token: jwt})
```

You don't need the call to `app_claims`. You can pass in perms directly - the `encode_and_sign` will populate the rest of the claims starting with app claims.

```
{ :ok, jwt, full_claims} = Guardian.encode_and_sign(user, :token, perms: %{ admin: [:all]})
```
