### ISSUE TITLE
put_resp_header error after api_sign_in

### ISSUE THREAD

**Issue by kevin-DL** [ueberauth/guardian#196]
Hello,
I am going through the simple api authentication blog post.

When i try to insert the header in to the response i get the following error
`** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Plug.Conn.put_resp_header/3`

My code looks like this

` defp update_user(conn, user, user_params) do

    changeset = User.changeset(user, User.format_info(user_params))
    case Repo.update(changeset) do
      {:ok, user_updated} ->
          new_conn = Guardian.Plug.api_sign_in(conn, user_updated)
          jwt = Guardian.Plug.current_token(new_conn)
          {:ok, claims} = Guardian.Plug.claims(new_conn)
          exp = Map.get(claims, "exp")

          new_conn = Plug.Conn.put_resp_header(new_conn,"authorization", "Bearer #{jwt}")
          new_conn = Plug.Conn.put_resp_header(new_conn,"x-expires", exp)
          new_conn
          |> render "loggedIn.json", user: user, jwt: jwt, exp: exp
        {:error, reason} ->
          conn
          |> put_status(401)
          |> render "error.json", errors: "Could not login"
    end

  end `

Do you have any idea?
Regards,
K

**Comment by keithalpichi** [comment]
You're passing `exp` as an integer and not a string. 
Fix it from this:
`Plug.Conn.put_resp_header(new_conn,"x-expires", exp)`
to this:
`Plug.Conn.put_resp_header(new_conn, "x-expires", "#{exp}")`

I'd also recommend to take advantage of the pipe operator like so:

```
conn
  |> put_status(200)
  |> put_resp_header("authorization", "Bearer #{jwt}")
  |> put_resp_header("x-expires", "#{exp}")
  |> render("loggedIn.json", %{user: user, jwt: jwt, exp: exp})
```

I'm sure this this function is in a controller and is `__using__` the `:controller` behavior. So you don't have to prefix `put_resp_header` with `Plug.Conn` as it's already imported. So just using `put_resp_header` will do like the example I gave above.

**Comment by kevin-DL** [comment]
@keithalpichi Thank you that fixed it.
It might be necessary to update the blog post though  i am probably the only one who would not notice.
Closing the issue

**Comment by keithalpichi** [comment]
@kevin-DL you're welcome. I agree with you. Hopefully the authors of the article see this issue and fix it.
