### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by GildedHonour** [ueberauth/guardian#197]
I can't get it to work. In my session controller I'm doing this, it's a simplified version:

      def new(conn, %{.....}) do
        case verify_login_and_password(conn, login, pass) do
          {:ok, usr} ->
            Guardian.Plug.sign_in(conn, usr)
            |> put_flash(:notice, "you've signed in")
            |> redirect("/")

That's all what I have basically. In my application layout I have this:

      <%= IO.puts("[debug] app.html Guardian.Plug.authenticated?: #{Guardian.Plug.authenticated?(@conn)}")%>

And it always returns false. What am I missing? In routes.ex I have 

   
    pipeline :browser_require_auth do
      plug(Guardian.Plug.VerifySession)
      plug(Guardian.Plug.LoadResource)

but they don't affect the sign in process itself, do they?

I've created the serializers also according to the documentation.

**Comment by hassox** [comment]
@GildedHonour did you get it sorted?

**Comment by GildedHonour** [comment]
Yes.
