### ISSUE TITLE
Git master doesn't install in Phoenix 1.2 app

### ISSUE THREAD

**Issue by denisw** [ueberauth/guardian#203]
When trying to install the git version of Guardian, I get the following error:

    Failed to use "phoenix" (version 1.2.1) because
      deps/guardian/mix.exs requires ~> 1.1.0
      Locked to 1.2.1 in your mix.lock

Is the library incompatible with Phoenix 1.2, or should `~> 1.1.0` maybe be `>= 1.1.0` or `>~ 1.1`?

**Comment by kevin-DL** [comment]
It works for me.
https://github.com/kevin-DL/phoenix_vue_template

**Comment by doomspork** [comment]
@denisw could you create a sample project that reproduces your issue for us to look at?

**Comment by denisw** [comment]
This seems to have been fixed by commit bfb31b4695383b883746a457f0bfead354c3f9c1. I am going to close the issue.
