### ISSUE TITLE
Best way to set expires_in for API response?

### ISSUE THREAD

**Issue by manuelsteiner** [ueberauth/guardian#207]
Hi,
sorry if this is not really the right place. It's rather an issue I'm not sure about how to tackle correctly.
My frontend requires an `expires_in` field in the response to a token request which is not the absolute expiration date but rather the relative time in seconds.

Is the correct way to handle this to read the default `ttl` from `config.exs` and convert whatever the `ttl` is to seconds or is there any built in function that I can user for that?

Thanks for the help and sorry for using the github issues for such a question.

**Comment by doomspork** [comment]
@manuelsteiner this isn't something I've personally run into so your suggestion of working back from `ttl` sounds reasonable.  @hassox have you done anything like this?

**Comment by manuelsteiner** [comment]
Thank you for the comment :)

**Comment by hassox** [comment]
Hey @manuelsteiner. Rather than using the ttl from the config, it's probably better if you read the exp field from the token and then subtract the current time from it.

**Comment by manuelsteiner** [comment]
Oh ok, thank you :) Will do it that way
