### ISSUE TITLE
Automatic login using "Remember Me" token

### ISSUE THREAD

**Issue by mitkins** [ueberauth/guardian#209]
I'm trying to follow the advice in #142 

I'm having trouble implementing the part where the new token is stored in the session and the page continues without redirect. Here's the crux of my current implementation:

    jwt = conn.req_cookies["remember_me"]

    case Guardian.decode_and_verify(jwt) do
      { :ok, claims } ->
        if ( claims |> Map.get("typ") == "remember" ) do
          { :ok, remember_user } = load_resource( conn, claims, opts )

          # This doesn't seem to do what I want
          conn |> Guardian.Plug.sign_in( remember_user )
        end

      { :error, reason } ->
        # Do something
    end

I have this in a Plug that runs after `LoadResource`. Although the code runs, it does not change the outcome. The page still redirects after `EnsureAuthenticated`

I'm assuming this has something to do with when the headers have been sent. Unfortunately I'm not familiar with Cowboy/Phoenix to know what I should do.

Full details are in this [SO question](http://stackoverflow.com/questions/39715722/guardian-remember-me-using-refresh-token).

Am I on the right track?

**Comment by nmqanh** [comment]
@mitkins I guess the code could be like this:

```elixir
defmodule MyApp.Plug.RememberMe do
  import Plug.Conn
  import Guardian.Plug

  def init(opts \\ %{}), do: Enum.into(opts, %{})

  def call(conn, _) do
    current_user = current_resource(conn)

    if ( current_user == nil ) do
      jwt = conn.req_cookies["remember_me"]
      case Guardian.decode_and_verify(jwt) do
        { :ok, claims } ->
          the_key = Map.get(claims, :key, :default)
          put_session(conn, Guardian.Keys.base_key(the_key), jwt)
      end
    end
  end
end
```
And in your pipeline, put your `MyApp.Plug.RememberMe` before `VerifySession`
Please try and see how it works 👍

**Comment by hassox** [comment]
I think you want to run it after VerifySession, since the session should be used before the remember me version. 

In general the idea is to find a token and verify it, or pass to the next plug to try and do the same.

Something like  

```elixir

defmodule Guardian.Plug.VerifyRememberMe do
  @moduledoc """
  Use this plug to load a remember me cookie and convert it into an access token

  ## Example

      plug Guardian.Plug.VerifyRememberMe

  You can also specify a location to look for the token

  ## Example

      plug Guardian.Plug.VerifyRememberMe, key: :secret

  This should be run after Guardian.Plug.VerifySession

  It assumes that there is a cookie called 'remember_me' and that it has a
  refresh type token
  """
  import Guardian.Keys

  @doc false
  def init(opts \\ %{}), do: Enum.into(opts, %{})

  @doc false
  def call(conn, opts) do
    key = Map.get(opts, :key, :default)

    if Guardian.Plug.authenticated?(conn, key) do
      # we're already authenticated somehow either from the session or header
      conn
    else
      # do we find a cookie
      jwt = conn.req_cookies["remember_me"]
      case exchange!(jwt, "refresh", "access") do
        {:ok, access_jwt, new_claims} ->
          conn
          |> Guardian.Plug.set_claims({:ok, new_claims}, key)
          |> Guardian.Plug.set_current_token(access_jwt, key)
        _error -> conn
      end
    end
  end

  defp exchange!(nil, _, _), do: {:error, :not_found}

  defp exchange!(jwt, from, to) do
    case Guardian.decode_and_verify(jwt, typ: from) do # only accept remember me tokens of typ "refresh"
      { :ok, claims } ->
        new_claims = claims
          |> Map.drop(["jti", "iat", "exp", "nbf"])
          |> Guardian.Claims.jti
          |> Guardian.Claims.nbf
          |> Guardian.Claims.iat
          |> Guardian.Claims.ttl

        {:ok, resource} = Guardian.serializer.from_token(new_claims["sub"])

        Guardian.encode_and_sign(resource, to, new_claims)
      error -> error
    end
  end
end
```

I'm making some assumptions about your token types and ttls and stuff here but I think it shows what _I think_ the general approach should be. 

I'd ultimately want to bring something like this into Guardian but it'll take a bit more than this since it has to take into account the ability to handle specific secrets etc.

(Also I haven't tested this code, just typed it for demonstration)

**Comment by mitkins** [comment]
Thanks @hassox. The above code works. The "typ" parameter in `decode_and_verify` just needed to be a map. @nmqanh based on @hassox's advice, I tried his solution first - thanks for taking the time though.

**Comment by ckruse** [comment]
So, how do I set a remember_me cookie with this code?

**Comment by ckruse** [comment]
Nevermind, got it working, thanks :)
