### ISSUE TITLE
Incorrect config example in README?

### ISSUE THREAD

**Issue by pcewing** [ueberauth/guardian#212]
Wanted to submit an issue to make sure this wasn't my own user error before making a pull request. In the README, one of the configuration examples is as follows:

``` elixir
## %JOSE.JWK{} Struct ##
# Useful if you store your secret key in an encrypted JSON file with the passphrase in an environment variable.

config :guardian, Guardian,
  allowed_algos: ["Ed25519"],
  secret_key: fn ->
    System.get_env("SECRET_KEY_PASSPHRASE") |> JOSE.JWK.from_file(System.get_env("SECRET_KEY_FILE"))
  end
```

The problem I am seeing is that `JOSE.JWK.from_file/2` returns a struct in the form of `{%JOSE.JWE{...}, %JOSE.JWK{...}}`, not just a `%JOSE.JWK{...}`.

```
iex> JOSE.JWK.from_file("my_pass", "my_key_file")
{%JOSE.JWE{...}, %JOSE.JWK{...}}
```

I updated my own config to look along the lines of:

``` elixir
  secret_key: fn ->
    {jwe, jwk} = 
      System.get_env("SECRET_KEY_PASSPHRASE")
      |> JOSE.JWK.from_file(System.get_env("SECRET_KEY_FILE"))
    jwk
  end
```

It's an easy fix but the resulting error isn't very obvious so it might save someone some time to update the example.

**Comment by doomspork** [comment]
@pcewing some changes have been merged into Guardian that should improve how this works.  If you'd like to submit a PR to further clarify in the README that would be welcomed 👍
