### ISSUE TITLE
Name collision using Guardian.Channel and Phoenix

### ISSUE THREAD

**Issue by kbredemeier** [ueberauth/guardian#214]
I am using phoenix v1.2.1 with ecto v2.0.5. I don't know if this issue existed before, but if I use `Guardin.Channel` in a phoenix channel I get the following error:

```bash
== Compilation error on file web/channels/visitors_channel.ex ==
** (Ecto.Query.CompileError) malformed join `authed_socket` in query expression
    lib/ecto/query.ex:551: Ecto.Query."MACRO-join"/6
    expanding macro: Ecto.Query.join/3
    web/channels/visitors_channel.ex:3: ExBalance.VisitorsChannel.join/3
```

This is because in `web/web.ex` phoenix imports `Ecto.Query` wich also defines `join/3`.
Currently I am solving this by changing the import to `import Ecto.Query, except: [join: 3] in `web/web.ex` inside the channel function.

Maybe the `join/3` call in `Guardian.Channel's` macro should be more explicit.

**Comment by doomspork** [comment]
Thanks for the heads up @kbredemeier, we'll have to look into this!  @hassox have you run into this yourself yet?

**Comment by hassox** [comment]
I haven't but it sounds like something that we should fix!

**Comment by doomspork** [comment]
@kbredemeier do you want to take a stab at a PR?  If not either @hassox or myself can make the change.
