### ISSUE TITLE
Move Plug and Phoenix code into another lib.

### ISSUE THREAD

**Issue by vic** [ueberauth/guardian#216]
Quoting the README file: `Guardian remains a functional system. It integrates with Plug, but can be used outside of it.`. However if the app does not depend on Plug nor Phoenix, a warning is emitted upon Guardian compilation: 

``` shell
=> guardian
warning: function Phoenix.Socket.assign/3 is undefined (module Phoenix.Socket is not available)
Found at 3 locations:
  lib/guardian/phoenix/socket.ex:71
  lib/guardian/phoenix/socket.ex:79
  lib/guardian/phoenix/socket.ex:87
```

One solution would be to move the Plug and Phoenix specific code from Guardian into another package, say `guardian_plug`. However, as I guess most people are using Guardian from inside a Phoenix app, I'm not sure if this is the right way to go. Also, moving the code out would require a major version change.

**Comment by doomspork** [comment]
@vic while I agree a warning is not pretty but I'm not sure if it warrants a wholly separate library.  @hassox do you have any thoughts?

**Comment by vic** [comment]
Yep I know, just was used to having nicely clean builds, but now with elixir 1.4 almost any dep I have has some warning (regarding the `()`) hopefully some day I'll have my eyes clean of warnings. :D cheers !
