### ISSUE TITLE
Create normal examples, videos, etc

### ISSUE THREAD

**Issue by OpakAlex** [ueberauth/guardian#218]
Guys, please create normal blog posts, examples, how to do `phoenix.new` and create auth flow. It will be so nice, for children which comes from `rails` way :) Thanks!

**Comment by doomspork** [comment]
Hi @OpakAlex!  There are some links in the README for resources plus a few blog post floating around.  We're working on some more in-depth lessons now 😀 

+ https://github.com/ueberauth/guardian#useful-articles
+ http://hassox.github.io/
