### ISSUE TITLE
Support {:system, VAR_NAME} idiom for secret_key

### ISSUE THREAD

**Issue by michalmuskala** [ueberauth/guardian#219]
It's a pretty common standard to support such a value in config for things that should be loaded from the environment. Secrets and seed values to algorithms are a common thing.

If you agree this would be useful, I can work on this.

**Comment by doomspork** [comment]
@michalmuskala all for this!  @hassox created a package to support this and we just never got around to incorporating it: https://github.com/hassox/config_values
