### ISSUE TITLE
Function references and anonymous functions are invalid in a sys.config

### ISSUE THREAD

**Issue by coryodaniel** [ueberauth/guardian#221]
I ran across an issue with generating an invalid `sys.config` file using a function reference or anonymous function as per the example:

``` elixir
config :guardian, Guardian,
  allowed_algos: ["Ed25519"],
  secret_key: fn ->
    # some cool way to get the key
  end
```

Got the error when working with [distillery](https://github.com/distillery) but found an [issue on exrm](https://github.com/bitwalker/exrm/issues/230) discussion the problem.

I saw another [ticket](https://github.com/ueberauth/guardian/issues/212) referencing invalid documentation, just figured I'd link it as well. 

I'm working on a fix now that would allow you to pass a tuple to secret key and call `apply/3` on it [here](https://github.com/ueberauth/guardian/blob/master/lib/guardian.ex#L299-L303).

Result will be:

``` elixir
config :guardian, Guardian,
  allowed_algos: ["Ed25519"],
  secret_key: {WayTo, :get, ["my", "key"]}
```

**Comment by coryodaniel** [comment]
PR: https://github.com/ueberauth/guardian/pull/222

**Comment by doomspork** [comment]
Thank you for the report @coryodaniel, I'll take a peek at your PR today 👍

**Comment by coryodaniel** [comment]
@doomspork I added another test case for something I missed ^
