### ISSUE TITLE
Authentication when resources are invalid works -- is this good?

### ISSUE THREAD

**Issue by roehst** [ueberauth/guardian#225]
Hi, I am working on a test case where the token has a user serialized by its id, and the token is signed, but the user is does not exist on the database. For example the user might have been deleted from the database but the cookie still exists on the client, containing a valid token.

My current understanding is that authentication is dependent on the token, with resources being loaded only if requested (using `current_resource`). I tried to play around with the hooks but didn't really manage to do it.

Is this intended? I am thinking if it makes sense to invalidate tokens when a user is deleted. Is it possible to do it like that?

Thanks

**Comment by doomspork** [comment]
Howdy @roehst!  This does work as intended for the reason you outlined.  Have you taken a peek at @hassox's other project GuardianDB?  It may provide some answers https://github.com/hassox/guardian_db
