### ISSUE TITLE
Release Schedule?

### ISSUE THREAD

**Issue by shantiii** [ueberauth/guardian#226]
As a user of guardian, it'd be really helpful to have a release schedule for guardian - so that I could know when/how often to check back and update my `mix.exs` dependency. This affects me moreso right now because I'm using bleeding edge features (I'm referring to master directly).  Do the maintaners see value in this? This ticket is mostly to open up discussion.

**Comment by doomspork** [comment]
@hassox / @scrogson — do you have any thoughts on a release schedule?  I think they're useful but with volunteer open source I think it can be tricky.

**Comment by doomspork** [comment]
We're not going to worry about release schedules for the time being.  When we get to 1.0.0 we can reconsider them.
