### ISSUE TITLE
Verifying custom tokens?

### ISSUE THREAD

**Issue by bobbypriambodo** [ueberauth/guardian#228]
Hello, I have an API that uses [`Phoenix.Token`](https://hexdocs.pm/phoenix/Phoenix.Token.html) (not JWT, although similar) for authentication. Suppose a client have already logged in and retrieved the token, it will send requests with `Authorization: Bearer <token>` header. I was wondering if I could use guardian for verifying such requests and denying unauthorized ones.

I think something along the way of implementing my own `verify_module`? But based on the description:

> verify_module - Provides a mechanism to setup your own validations for items in the token. Default is Guardian.JWT

I get the idea that it essentially assumes we're still using JWT, therefore I don't think it's the correct way. I know I could just write some plugs for verification myself, but I'm curious if this use case is handled by guardian (or other libraries).

**Comment by doomspork** [comment]
@bobbypriambodo as-is Guardian will not work with Phoenix.Token.  While the `verify_module` allows you to configure the verification step, it is still relying on a JWT being decoded: https://github.com/ueberauth/guardian/blob/5f9488ab253a0ef6c7e97bb8184d8c7320dbbfd3/lib/guardian.ex#L227-L229

I'm not sure Guardian is the right place for this functionality seeing as we've built the library around JWTs.  If it's not too late I'd ditch `Phoenix.Token` in favor of JWT.  JWT will be supported across any platform you work with (even if you were to migrate away from Phoenix) whereas the same cannot be said for a `Phoenix.Token` (AFAIK).

**Comment by bobbypriambodo** [comment]
Thank you for the answer, @doomspork. You are right that JWT will be more cross-platform compatible than Phoenix.Token, but sometimes (like in my use case) we only need basic token signing and verifying mechanisms without extra deps, and Phoenix.Token fits the bill nicely. I was wondering if all the niceties of Guardian (`VerifyHeader`, `EnsureAuthenticated`, etc.) will work with it. I end up writing my own library for it (mostly for my learning too).

Thanks again, by the way! I'm closing this if you don't mind.
