### ISSUE TITLE
Setting cookies for other domains

### ISSUE THREAD

**Issue by madshargreave** [ueberauth/guardian#230]
Hi

I have a third-party JS script that my customers can install on their site to track their own users.

Previosuly I have been using localstorage for this purpose, but that does not work cross-domain, so now I am looking into using cookies.

I have however not been able to find a way to set the domain on the cookie (which AFAIK is required when setting cookie for another domain)

Is this possible?

**Comment by scrogson** [comment]
@madshargreave sounds like you are looking for the `domain` option on `Plug.Session`: https://hexdocs.pm/plug/Plug.Session.html#module-options
