### ISSUE TITLE
Timeoutable

### ISSUE THREAD

**Issue by ericsullivan** [ueberauth/guardian#236]
I'm creating a timeoutable module. It's really just a plug, and a hook into after_sign_in

I had a couple questions.
1) Is it worth adding that to Guardian? If not, is guardian_timeoutable an acceptable name?

2) The hook only needs to fire when there's a session. I think I can use
```
if conn.private[:plug_session]
```
But that seems a little iffy... There are two functions that call the hook, Guardian.Plug.api_sign_in and Guardian.Plug.sign_in. Is it worth passing an extra parameter to the callback which specifies session or api login?

**Comment by doomspork** [comment]
Howdy @ericsullivan!  As of now there is no plans to expand the scope of Guardian but I have no objections to your using that package name.  We can create a section in the README/Wiki for Guardian plugins, does that seem reasonable to you?

Any thoughts @hassox?
