### ISSUE TITLE
Confirmable / Approvable

### ISSUE THREAD

**Issue by ericsullivan** [ueberauth/guardian#237]
One more question :)

I'm also creating a module that requires a user is approved before they log in. These same questions apply to confirmable or any other sort of hook that prevents login if a condition isn't met on the user. I was going to use a plug and hooks

for the plug, is the best way to use the pattern in VerifySession? Namely:
```
if not approved?
conn
|> Plug.Conn.delete_session(base_key(key))
|> Guardian.Plug.set_claims({:error,'Not Approved'}, key)
```

and for the hook
```
def after_sign_in(conn, key)
  if not approved?
    conn |> sign_out_via_key(key)
 or
   conn |> sign_out(key)
 or
   something else?
end
```

**Comment by doomspork** [comment]
This seems reasonable to me @ericsullivan 👍
