### ISSUE TITLE
Release 0.13.1

### ISSUE THREAD

**Issue by kenips** [ueberauth/guardian#239]
It seems like 0.13.1 is not released but documented in changelog as a release? I'm running into #221 and would appreciate a release. Thanks!

**Comment by mariusbutuc** [comment]
`0.13.1` is [the one currently declared](https://github.com/ueberauth/guardian/blob/5f9488ab253a0ef6c7e97bb8184d8c7320dbbfd3/mix.exs#L4), but there is no tag/release for it. 

If #222 is the working fix for #221, releasing `0.13.1` would be amazing! 😸 

Thanks @hassox, @doomspork, @scrogson & Co. ✌️

**Comment by doomspork** [comment]
@kenips / @mariusbutuc — I'm going to cut 0.14 this weekend with a bunch of changes and bumping the Elixir version to 1.3.

**Comment by mariusbutuc** [comment]
With [v0.14.0](https://github.com/ueberauth/guardian/releases/tag/v0.14.0) released, we might be good to close this.

**Comment by doomspork** [comment]
Thank you @mariusbutuc 👍
