### ISSUE TITLE
Prevent reuse of cookie to authenticate after logout

### ISSUE THREAD

**Issue by smoes** [ueberauth/guardian#251]
Recently, we had a professional pentest company checking our application. One security flaw in our application is that a former properly authenticated user-cookie can be used to be re-authenticated even after logout (`via sign_out`), without using the official login-route (by simply injecting it into the browser). 

Is it possible to prevent such a re-authentication using "cookie-injection" of a former authentication-cookie, without changing our application data-model/logic?

**Comment by doomspork** [comment]
Hi @smoes, have you taken a look at the [GuardianDB](https://github.com/ueberauth/guardian_db) project?  With GuardianDB you can track tokens and prevent playback

**Comment by smoes** [comment]
Oh actually we have not!
Looks good, thank you for the advice @doomspork . We will have a look at it, but at a first glance it seems to be exactly what we needed!

**Comment by doomspork** [comment]
You're welcome @smoes! 👍

**Comment by hassox** [comment]
@smoes this was the reason we developed guardian db. By tracking all the issued valid tokens sign out will revoke them. Part of the challenge of using JWT is that they are essentially untracked unless you do it in your app and will stay valid until they reach expiry.
