### ISSUE TITLE
Umbrella app configuration

### ISSUE THREAD

**Issue by lukerollans** [ueberauth/guardian#258]
I was just wondering if it was possible to configure Guardian on a per app basis in the context of an umbrella?

In my umbrella, I have two apps which both define a unique User resource which are handled independently as far as authentication is concerned. I've had to create another app in the umbrella to handle serialization (via Guardian) which depends on the two aforementioned apps.

Because of this, I can no longer run the entire test suite of each application (tests which rely on authentication fail) given they don't know the "auth" app exists. It's an unresolvable circular dependency.

The build is still green when tests are run from the umbrella root, so it's not a gigantic issue, but I would ideally also like to retain the ability to run the test suite of each app in the umbrella independently. That is, the authentication tests in each umbrella app.

### Example
```elixir
defmodule Lunchbox.Auth.GuardianSerializer do
  @behaviour Guardian.Serializer

  alias Lunchbox.Repo

  def for_token(user = %Lunchbox.Catering.User{}) do
    {:ok, "CateringUser:#{user.id}"}
  end
  def for_token(user = %Lunchbox.Admin.User{}) do
    {:ok, "AdminUser:#{user.id}"}
  end
  def for_token(_),  do: {:error, "Unknown resource type"}

  def from_token("CateringUser:" <> id) do
    {:ok, Repo.get(Lunchbox.Catering.User, id)}
  end
  def from_token("AdminUser:" <> id) do
    {:ok, Repo.get(Lunchbox.Admin.User, id)}
  end
  def from_token(_), do: {:error, "Unknown resource type"}
end
```

This is my serializer module inside the `auth` app of my umbrella. The `catering` and `admin` apps define `Lunchbox.Catering.User` and `Lunchbox.Admin.User` respectively.

Because `auth` depends on both `{:catering, in_umbrella: true}` and `{:admin, in_umbrella: true}` so that it can see the above structs, neither `catering` nor `admin` can depend on `auth` which would solve my issue.

### Ideal outcome
What I would like to do is create a unique serializer module for each application and delete the `auth` app altogether. However, afaik there's no way to configure Guardian that way. 

If I do, whichever app happens to run second will stomp all over the config for the first app, which would configure `admin` to load up the serializer for `catering`, for example.

**Comment by scrogson** [comment]
Definitely agree here. The current configuration for Guardian is subpar as it is only available globally. This is something we are planning to change for a 1.0 milestone.

**Comment by lukerollans** [comment]
That's fantastic news. I solved the above by moving everything to the one app which is less than _perfectly_ ideal, but it's also OK.

Looking forward to refactoring once 1.0 hits 👍

**Comment by kuffel** [comment]
I had a similiar issue. It can be solved by updating your umbrella configuration files in this way:

For example you have an umbrella app with two websites using guardian an other apps that are being used by them, e.g.

website_a (using guardian)
website_b (using guardian)
common_app_a
common_app_b

In config.exs of your umbrella, remove this line:

    import_config "../app/*/config/config.exs"

And replace with these

    import_config "../app/common_app_a/config/config.exs"
    import_config "../app/common_app_b/config/config.exs"

Now change the mix files of the to website apps to just import their own configs:

    config_path: "config/config.exs"

Then in the config.exs of the two website apps add this line 

    import_config "../../../config/config.exs"

It would be much easier if guardian would try to figure out in which module it is being used. `Application.get_all_env :guardian` returns a list with two guardian configurations, so i think it should be possible to pick the correct config.

**Comment by hopewise** [comment]
In my case, it's not an umbrella app, but one app with multiple endpoints.
How would I have multiple configurations for Guardian in one app?

**Comment by odarriba** [comment]
Hi!

I've been with this issue (I'm developing an umbrella app with multiple Endpoints that use Guardian in a different way).

What do you think about making some parts of the `Guardian` lib (the ones that read and directly use the config) as part of a macro, (which can read the config using a parameter and __MODULE__, as Ecto does).

Then it can be used in a module like:

```elixir
defmodule WadusApp.Guardian do
  use Guardian, otp_app: :wadus_app
end```

and call that class from plugs by passing it as parameters, execute things like `WadusApp.Guardian.sign_in(conn, object)` , etc.

What do you think about that point of view to solve this?

**Comment by hassox** [comment]
Something like this is what we've been thinking for  1.0

The global config is too limiting

**Comment by odarriba** [comment]
any ETA? so you accept PR in case I can dedicate some time to this?

**Comment by scrogson** [comment]
Starting work on this.

**Comment by odarriba** [comment]
Any updates on this?

**Comment by hassox** [comment]
Hey @odarriba 

Work is progressing on V1 which includes the ability to have multiple configurations in a single app. There are three remaining items left.

1: the Phoenix helpers
2: permissions
3: updating guardian db

I expect that these will be finished and an rc will be released later next week.

**Comment by odarriba** [comment]
Thanks for the update @hassox !
Looking forward to see the RC and start using it for our multi-app umbrella project 😄

**Comment by scrogson** [comment]
Now available on `master` and will be published to Hex very soon™.
