### ISSUE TITLE
API Sign Out

### ISSUE THREAD

**Issue by asummers** [ueberauth/guardian#260]
Is there a purposeful omission of this function? In general I could see the argument that signing out a JWT in an API fashion doesn't make quite as much a difference, because the JWT will continue to exist on the client, potentially. However, in the context of something like GuardianDB, it would make sense. Given that the hooks exist around signing out, and there exists `api_sign_in`, `sign_in` and `sign_out`, I think we should include an `api_sign_out` function as well that verifies and calls `revoke!`, with the relevant hooks interspersed.

**Comment by artukrap** [comment]
@asummers Agree with you and would love to see this functionality

**Comment by doomspork** [comment]
@asummers I do not believe that was left out intentionally (@hassox?), if you'd like to open a PR with that addition that'd be stellar 👍

**Comment by Moxide** [comment]
In my apps, I use ```Guardian.revoke!```, isn't it what you're looking for ?

**Comment by artukrap** [comment]
@Moxide Yes, it's same. I guess here we talk more about convention and helper function.

**Comment by Moxide** [comment]
Oh ok, I read the initial post too quickly ;-)

**Comment by scrogson** [comment]
I think I would prefer to see `api_sign_in` removed in favor of a single `sign_in` with a `session: false` option. `api_sign_out` doesn't seem to make any sense to me.

**Comment by scrogson** [comment]
Closing for now.
