### ISSUE TITLE
Control Flow of Library

### ISSUE THREAD

**Issue by asummers** [ueberauth/guardian#262]
For various reasons, GuardianDB didn't quite work out of the box for our use case, so I've been bouncing around the library for the past few days debugging various things. One thing that was really hard to do, though simple in nature, was actually traverse calls of the various plugs, hooks, etc. It became very hard to recall where you came from exactly, as things seemed almost cyclic in nature, with plugs calling into guardian, calling into hooks, eventually calling into plugs, etc. One thing that I believe would make things much easier to reason about would be a policy that things cannot reach up into `guardian.ex`. Instead, when that happens, `guardian.ex` and whatever else should reach into common helper libraries. I believe the same should be true of the plug functions, with the conceptual model of a larger application with a public API of the plugs and `guardian.ex`. I realize I'm proposing breaking public APIs potentially, which is not something I suggest lightly, but pre 1.0 is the only time to do that. 

Another issue was the heavy use of private functions for things like actual decoding of the token. Having that in a public module would have helped our cause, and would enable independent testing for guardian internals.

**Comment by doomspork** [comment]
@asummers thanks for opening this!  @hassox and I have been discussing what v1.0 would look like lately and this is certainly something to take into consideration.

**Comment by scrogson** [comment]
@asummers thank you for your feedback. We will be pushing towards 1.0 soon and have been in discussion about making things better in many areas. Simplifying the API is a huge priority for us.
