### ISSUE TITLE
Verify registered claims like "exp"

### ISSUE THREAD

**Issue by Grafikart** [ueberauth/guardian#263]
Hi, I'm using guardian with JWT and I want to know if the library contains a way to force registered claims to be filled. For instance reject claims without `exp`. I created my own `plug` but I wanted to be sure Guardiant doesn't handle this already (couldn't find anything in the documentation about this).

**Comment by hassox** [comment]
Hi @Grafikart 

Guardian comes with the ability for you to specify your own module to check claims. In the configuration it is: 

```elixir
verify_module: Guardian.JWT
```

This is a simple implementation of the `Guardian.ClaimValidation` behaviour. If you require different or more stringent checks on claim validation you can `use Guardian.ClaimValidation` and overwrite the `validate_claim` function to do what you need. https://github.com/ueberauth/guardian/blob/master/lib/guardian/claim_validation.ex has all the default implementations.

https://github.com/ueberauth/guardian/blob/master/lib/guardian/jwt.ex

**Comment by Grafikart** [comment]
Thanks
