### ISSUE TITLE
Using a claim other then "sub" in LoadResource

### ISSUE THREAD

**Issue by bryanjos** [ueberauth/guardian#268]
I have a project where I am given a JWT from Auth0. The claim that contains the value used to find a user is not in `sub` so we could not use LoadResource as is. I wanted to know if it makes sense to make the claim that LoadResource looks for customizable? If so, I can make a PR for it.

**Comment by doomspork** [comment]
Thanks @bryanjos!  I don't see any issues with this being customizable so long as we retain a san default.  @hassox any thoughts?

**Comment by scrogson** [comment]
@bryanjos this sounds like a good idea to me. PR welcome.

**Comment by bryanjos** [comment]
@scrogson sorry for the delayed response, I can put a PR in as soon I get a chance.
