### ISSUE TITLE
How does this library work?

### ISSUE THREAD

**Issue by ghoshnirmalya** [ueberauth/guardian#269]
This is rather for a discussion than an issue. Feel free to close it if this seems the wrong place to ask this doubt.

I've used `ueberauth` for my login with Google. Now, after signup/signin, I'm generating a token and send it as the response.

Now, for my `api_auth` pipeline which is only for the authenticated users, I'm using `plug Guardian.Plug.EnsureAuthenticated` in my controllers. 

1. Will the authenticated user be able to see those pages if the `Authorization: Bearer <jwt>` is sent in the request?
2. How do I control session?

I'm asking this since my backend Elixir app is an api-only app. 

Link to the repo: https://github.com/ghoshnirmalya/social_app_api.

**Comment by ghoshnirmalya** [comment]
Okay. So, I made the login to work and now, I can only see my authenticated routes after I provide the `Authorization: Bearer <jwt>` in the header. But, I can't make the sign out to work. I know that I can just forget the token from the client itself but how can I remove the user from the session in the API itself.

Also, do you suggest using [guardian_db](https://github.com/ueberauth/guardian_db) to handle sessions?

**Comment by scrogson** [comment]
Hi @ghoshnirmalya,

Yes, GuardianDB is recommended for preventing replaying of tokens. You can read a bit more about that [here](http://blog.overstuffedgorilla.com/simple-guardian-api-authentication/). The very last section of that post has a good explanation of why it's necessary.

Hope that helps.
