### ISSUE TITLE
Where is the jwt token or claim stored in assigns?

### ISSUE THREAD

**Issue by mikeni** [ueberauth/guardian#270]
In the docs, for Guardian.Plug.api_sign_in, it mentions that the jwt token or claim data is stored in assigns,  
https://github.com/ueberauth/guardian/blob/master/lib/guardian/plug.ex#L135

I don't see it under assigns, however I do see it storing in
conn[:private][:guardian_default_claims]
and
conn[:private][:guardian_default_jwt]

are we supposed to look in assigns or private for jwt data?

**Comment by scrogson** [comment]
@mikeni that is a typo. The `claims`, `token`, and `current_resource` are set using `Plug.Conn.put_private/3`.

However, you should not generally rely on those implementation details. Each of those fields has a public API:

```ex
Guardian.Plug.current_token(conn)
Guardian.Plug.claims(conn)
Guardian.Plug.current_resource(conn)
```

**Comment by scrogson** [comment]
@mikeni I've pushed this commit https://github.com/ueberauth/guardian/commit/68412b72fc5b1f9bd4203729debdd02ac4ffec9a to hopefully remove the confusion about `assigns` vs. `private`.

**Comment by mikeni** [comment]
@scrogson thanks for clearing that up
