### ISSUE TITLE
Testing phoenix channels: current_resource in channel test?

### ISSUE THREAD

**Issue by mikebaldry** [ueberauth/guardian#271]
I'm testing a socket with the standard `subscribe_and_join` method, but I've got no idea how to set the authenticated user of the socket in the test, as predicted, `current_resource(socket)` returns `nil`... Any pointers? I can't find any documentation on this

Many thanks and great work 👍

**Comment by mikebaldry** [comment]
I've just found `set_current_resource` which looks like just the ticket, it sets the assigns correctly, but when I actually get inside my `handle_in`, the assigns is empty again?

**Comment by scrogson** [comment]
@mikebaldry some examples of your current usage would be helpful.

**Comment by jstr** [comment]
@mikebaldry the implementation example here worked for me: https://github.com/hassox/phoenix_guardian/blob/ueberauth-guardian/test/channels/authorized_channel_test.exs
