### ISSUE TITLE
does not load with phoenix 1.3.0-rc.0

### ISSUE THREAD

**Issue by kokolegorille** [ueberauth/guardian#274]
While playing with phoenix 1.3.0-rc0, I added guardian dependency. It gaves the error:

guardian (versions 0.14.0 to 0.14.2) requires ~> 1.2.0

Just to mention for those using cutting edge...

**Comment by gregstula-autoreleasepool** [comment]
I too ran into this issue on a new 1.3 project. I was surprised to see it not work

**Comment by doomspork** [comment]
This has been addressed in a prior issue: https://github.com/ueberauth/guardian/issues/273
