### ISSUE TITLE
Phoenix 1.3

### ISSUE THREAD

**Issue by EvertYipYip** [ueberauth/guardian#276]
Dependency resolution fails with elixir 1.3

`Failed to use "phoenix" (version 1.3.0-rc.0) because
  apps/.../mix.exs requires ~> 1.3.0-rc
  guardian (version 0.14.2) requires ~> 1.2.0
  phoenix_live_reload (version 1.0.8) requires ~> 1.0 or ~> 1.2-rc`

**Comment by doomspork** [comment]
@EvertYipYip this is now the third issue created for 1.3, please check the previous issues: https://github.com/ueberauth/guardian/issues/274
