### ISSUE TITLE
Compatibility with Pheonix 1.3

### ISSUE THREAD

**Issue by sphinxc0re** [ueberauth/guardian#279]
Since [Pheonix 1.3](https://github.com/phoenixframework/phoenix/releases) is going to be released soon, when will guardian become compatible with it? Currently I'm unable to use it because I already adopted the RC-1 of Phoenix 1.3
```
> mix deps.get
Running dependency resolution...

Failed to use "phoenix" (version 1.3.0-rc.1) because
  guardian (version 0.14.2) requires ~> 1.2.0
  phoenix_live_reload (version 1.0.8) requires ~> 1.0 or ~> 1.2-rc
  mix.lock specifies 1.3.0-rc.1

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
*
```

**Comment by doomspork** [comment]
Please see the other issues on 1.3 compatibility: https://github.com/ueberauth/guardian/issues/273

**Comment by sphinxc0re** [comment]
Oh, snap! I did issues wrong again 😅 Thanks for your quick help @doomspork
