### ISSUE TITLE
Can guardian work with Fernet?

### ISSUE THREAD

**Issue by Hostert** [ueberauth/guardian#281]
Hello.

[This post](https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid) exposes JWT as insecure and suggests the use of Fernet as alternative.

Can guardian work with Fernet naturally or be adapted for it? Or am I talking nonsenses?

### Fernet links:

- https://github.com/fernet/spec
- https://hexdocs.pm/fernetex/
- https://hexdocs.pm/fernet_ecto/

**Comment by doomspork** [comment]
At first glance it looks like Fernet would require a bit of work but it doesn't look impossible.  How would you propose using Fernet @Hostert?  If you generate a JWT and then apply Fernet to that, it doesn't look like much work at all.

**Comment by Hostert** [comment]
Hey @doomspork, I'm still new to Elixir and guardian, so I can't do any valid suggestion, I think. But, as guardian documentation says, "The core currency of authentication in Guardian is JSON Web Tokens (JWT)." 

So, in `config.exs` instead of using the optional `verify_module: Guardian.JWT`, we could use something like `verify_module: Guardian.Fernet`, or just `verify_module: Fernet`.

But, as I said, I don't have enough knowledge to point this as a valid suggestion.

And as you say in 
> If you generate a JWT and then apply Fernet to that...

If we do this, we still have, hypothetically, a JWT insecure token?

**Comment by doomspork** [comment]
@Hostert Guardian is closely tied to JWT, it's more than just verifying the token.

What would you use Fernet to hash?  How would hashing that generic value differ from hashing a JWT with Fernet?

**Comment by Hostert** [comment]
@doomspork 

> it's more than just verifying the token.

I see. Unfortunatelly, I did not understand exactly why JWT is insecure or the ways it could be a problem to us. I'm using guardian the way it is. I just asked this because I wanted to understand why, or in which way Fernet could be used in replacement of JWT.

I would like to help you with any suggestion, but if you don't know exactly how to answer this issue, we can close this for now. No hard feelings :smile:

Maybe in future someone can make usefull sugestions.

**Comment by doomspork** [comment]
We'll keep and eye on this and we can revisit in the future @Hostert 👍
