### ISSUE TITLE
Is there a way to validate a token ignoring the expiration date?

### ISSUE THREAD

**Issue by agusguerra10** [ueberauth/guardian#283]
Is there a way to validate a token ignoring the expiration date? Or can anybody tell me if there's an easy modification I could make to the library to allow this?

Thanks!

**Comment by scrogson** [comment]
@agusguerra10,

Can you give some more details why you would want to do this? That seems like a major security vulnerability.

**Comment by agusguerra10** [comment]
I know it's not the best thing considering security but it's something I am willing to leave aside in this particular case.

I have lots and lots of users with an expired token, resulting with them being logged out of the app. I need this users to get a new token without having them to enter their credentials again, so ignoring the token expiration date or being able to refresh a token with an old (not valid anymore) one would help me accomplish that. Does it make sense?

Thanks.

Agus.

**Comment by scrogson** [comment]
That is not something I recommend and is definitely not in scope for Guardian.

If you really "need" that, you can define your own claim validation module and configure Guardian to use that:

```ex
config :guardian, Guardian,
  ...
  verify_module: MyApp.ClaimValidator
```

Have a look at `Guardian.JWT` and `Guardian.ClaimValidation`.
