### ISSUE TITLE
Always get unauthorized

### ISSUE THREAD

**Issue by hopewise** [ueberauth/guardian#285]
In config.exs:

> config :guardian, Guardian,
>   allowed_algos: ["HS256"], # optional
>   verify_module: Guardian.JWT,  # optional
>   issuer: "MyApp-Business",
>   ttl: { 10, :years },
>   allowed_drift: 2000,
>   verify_issuer: true, # optional
>   secret_key: "xxxxxxxxxxxxxxxxxxxxx",
>   serializer: Trackware.GuardianSerializer

In route:

>  pipeline :api do
>     plug Guardian.Plug.VerifyHeader, realm: "Bearer"
>     plug Guardian.Plug.LoadResource
>     plug Guardian.Plug.EnsureAuthenticated
>     plug :accepts, ["json-api"]
>   end
> 
> scope "/api", MyApp do
>     pipe_through :api
>     post "/csvs", CsvsController, :create
> end

Unfortunately, I just get Unauthorized, although I am using the same secret key and algo when creating the sent token.

Any idea? or at least, how to debug this?

**Comment by hassox** [comment]
Hey there. Without any more information I'm wondering if setting it to 10 years is perhaps too long. Have you tried shortening the token life to maybe a month?

**Comment by hassox** [comment]
If you could, what is the error reason from decide and verify?

**Comment by hopewise** [comment]
I tried shortening it to 2 months, I still get `Unauthenticated` error.
Then, I found that the `issuer` in settings does not match the `issuer` in token! So, that was the problem, and I have fixed it, thanks.

**Comment by thomasdola** [comment]
@hopewise how did you fix it?
