### ISSUE TITLE
badmatch when connect to socket

### ISSUE THREAD

**Issue by hopewise** [ueberauth/guardian#287]
I tried to use it with socket, when I do `sign_in` as:

```
def connect( %{"guardian_token" => jwt} = params, socket) do 
  case sign_in(socket, jwt) do
      {:ok, authed_socket, guardian_params} -> {:ok, authed_socket}
      m ->
        #unauthenticated socket
        IO.inspect m
        
      {:error, "auth error"}
   end
```
I got error:
```
{:error,
 %CaseClauseError{term: {:error,
   {:badmatch,
    <<5, 230, 171, 122, 183, 178, 39, 71, 151, 2, 35, 162, 36, 165, 117, 66, 34,
      194, 38, 22, 198, 114, 35, 162, 36, 133, 51, 35, 83, 98, 39,
      13::size(4)>>}}}}
```

I try to connect as:

    ws://192.168.1.32:4000/socket/websocket?guardian_token=Bearer xxx&vsn=1.0.0

I am sure that the token works fine, as I already tried it successfully in rest call for an api at a controller.

Any idea?

**Comment by scrogson** [comment]
@hopewise,

It looks like the problem is that you have `Bearer ` prefixed to the token. That should only be the value when used as an `Authorization` header.
