### ISSUE TITLE
Failed to use "phoenix" (version 1.3.0-rc.1)

### ISSUE THREAD

**Issue by ponty96** [ueberauth/guardian#288]
I'm having issues using Guardian with `Phoenix 1.3.0-rc.1`
<img width="923" alt="screen shot 2017-04-20 at 8 41 38 pm" src="https://cloud.githubusercontent.com/assets/11190968/25249446/c79bdf22-2609-11e7-9e08-ef2a45c236b1.png">

**Comment by johannesE** [comment]
I am having the same Problem. @ponty96 Why did you close this?

**Comment by dfcarpenter** [comment]
@johannesE I did but I also made another change to uuid because I was using cqex which is a cassandra client for elixir. It relies on cqerl which in turn uses an erlang lib called :uuid which causes problems on compile. Thus I had to for the elixir uuid  ( the one on hex.pm ) and rename it.

**Comment by johannesE** [comment]
@dfcarpenter Okay, thanks for your explanation. I'll create a small PR for guardian in this case.

**Comment by odarriba** [comment]
Just created a PR #293 about this.

**Comment by johannesE** [comment]
Oh no. Now we have #292 and #293. Two rejected PR's.
For any future visitors: The resolution is to use `override: true`:
` [{:phoenix, "~> 1.3.0-rc", override: true}` until the new phx version comes out.

**Comment by johannesE** [comment]
@sergiotapia it overrides the version of the dependencies. So if guardian has phoenix ~> 1.2 defined (which does not include rc's and betas, but 1.3.0 would be used), then we are telling mix that it's okay to use phoenix 1.3.0-rcx for guardian and all the other packages that depend on phoenix. That's how I understood this.

**Comment by sergiotapia** [comment]
Thank you
