### ISSUE TITLE
Use Guardian without Model

### ISSUE THREAD

**Issue by Linbubin** [ueberauth/guardian#290]
Hello,   This problem is similar to #163 ,
I use Guardian in phoenix. My project is to use an interface to verify that the user name and password are matched, if the authentication success to enable users to log on and continue to visit other page.
And I write
```
@behaviour Guardian.Serializer

def for_token(id), do: {:ok, id}

def from_token(id), do: {:ok, id}
```
but I don't know how to write conn |> Guardian.Plug.sign_in(%{??????}) in SessionController When the user verifies.
And when user log out is `conn |> Guardian.Plug.sign_out |> render(...)` ?

route.ex: 
```
defmodule HelloPhoenix.Router do
  use HelloPhoenix.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

pipeline  :login_required do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    # current_user = current_resource(conn)
    # assign(conn, :current_user, current_user)
    plug HelloPhoenix.CurrentUser  
    plug Guardian.Plug.EnsureAuthenticated, handler: HelloPhoenix.GuardianErrorHandler
  end

scope "/", HelloPhoenix do
    pipe_through [:browser]

    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:new, :create,:delete]

    # user require login
    scope "/" do
      pipe_through [:login_required]

      resources "/product", ProductController
```
I don't know how to wirte my routes, may be `pipeline  :login_required` should be split？
It drives me crazy。
I asked a few questions, you can answer one or a few, of course, the best answer all。

## question:
1. how to write SessionController create `conn |> Guardian.Plug.sign_in( ?????)` when user authentication.
2. how to write SessionController delete `conn |> Guardian.Plug.sign_out( ????? )` when user log out.
3. how to write routes pipeline and distribute them.

anyway thanks :)

**Comment by b-murphy** [comment]
@Linbubin have you explored using a Struct in place of the Ecto example? will post example shortly if not.

**Comment by Linbubin** [comment]
@b-murphy  sorry, I dont find  example, can you post some links?

**Comment by Linbubin** [comment]
I just write when someone is authenticated.
```
 conn
      |> Guardian.Plug.sign_in(%{ok: "username"})
      |> redirect(to: page_path(conn, :index))
```

and when people log out 
```
conn
    |> Guardian.Plug.sign_out 
    |> put_layout(false)
    |> render("login.html")
```
routes:
```
defmodule Zerg.Router do
  use Zerg.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :login_required do
    plug Guardian.Plug.EnsureAuthenticated, handler: Zerg.GuardianErrorHandler
  end

  scope "/", Zerg do
    pipe_through [:browser, :with_session] # Use the default browser stack

    get "/login", SessionController, :index
    post "/login", SessionController, :login
    get "/trading_systems/:trading_system_id/subscribe", TradingSystemController, :subscribe

    scope "/" do
      pipe_through :login_required

      get "/", PageController, :index
    end
  end
end
```
It achieve what I expected, but I don't think it's the right way to write, even I don't use Guardian.Plug.current_resource( This is not necessary？).

who can give me some advice ?

**Comment by b-murphy** [comment]
@Linbubin here is a possible example ~

Firstly if you use a basic struct to define your user
```
defmodule MyApp.User do
  defstruct id: "1"
end
```
With this you can pass it into the serializer through the `Guardian.Plug.sign_in`
```
defmodule MyApp.SessionController do
  def create(conn, params = %{}) do
    case params["password"] == Application.get_env(:my_app, :master_password) do # don't do exactly this to validate your password
        true ->
           user = %MyApp.User{id: "1"}
           conn
           |> Guardian.Plug.sign_in(user) # pipe the conn & user into the session
           |> redirect(to: "/dashboard)
        false ->
          # do fail redirect
     end
  end
end
```
Then within your serializer you will need to define a way to serialize the user struct
```
defmodule MyApp.GuardianSerializer do
  @behaviour Guardian.Serializer

  alias MyApp.User

  def for_token(user = %User{}), do: { :ok, "User:#{user.id}" }
  def for_token(_), do: { :error, "Unknown resource type" }

  def from_token("User:" <> id), do: { :ok, %User{id: id} }
  def from_token(_), do: { :error, "Unknown resource type" }
end
```
This is an imperfect solution & i feel that perhaps you are more looking for basicAuth on your application. Also i spotted that you use `username` with your examples, i would say that if you need to check different usernames into the session, perhaps consider using Ecto for your user storage.
hope this helps.

**Comment by Linbubin** [comment]
@b-murphy Thanks very much.
if I create a user table just store username, it's ok?
```
defmodule MyApp.SessionController do
  def create(conn, %{"username" => username } = params) do
    case  API.return do
        true ->
           case Repo.insert(MyApp.User.changeset(%{username: username})) do
             {:ok, user} ->
                conn
                |> Guardian.Plug.sign_in(user) # pipe the conn & user into the session
                |> redirect(to: "/dashboard)
             {:error, _} ->
                # do fail redirect
        false ->
          # do fail redirect
     end
  end
end
```
but Guardian.Plug.current_resource use where? (automatic call when loading page?)

**Comment by b-murphy** [comment]
@Linbubin think perhaps you are best to start from the beginning and follow this guide perhaps ~ http://blog.overstuffedgorilla.com/simple-guardian/

**Comment by Linbubin** [comment]
@b-murphy  ok， thanks
