### ISSUE TITLE
Relax phoenix dependency to 1.3

### ISSUE THREAD

**Issue by maxnordlund** [ueberauth/guardian#295]
Phoenix 1.3 has a release candidate, and it would be nice if you could use Guardian with it. I don't think there should be any problems, as it's Plug based, but it's hard to tell until you've tried it for real.

Thoughts?

**Comment by doomspork** [comment]
@maxnordlund please see one of the many issues on Phoenix 1.3 where this has been discussed: https://github.com/ueberauth/guardian/issues/288

**Comment by maxnordlund** [comment]
Ah, thanks.

**Comment by maxnordlund** [comment]
All though, considering the amount of issues I found, it might be good to relax the constraint anyways.

**Comment by doomspork** [comment]
There's no plan to do that @maxnordlund but thank you.  Issues like this come up when using Elixir all the time, it's important to handle it the proper way (as mentioned in those issues) and not force packages to loosen their dependencies.

**Comment by maxnordlund** [comment]
True, but from what I could tell by reading through those issues, there seem to be no issue with using Guardian with 1.3. Anyway, sooner or later it will be released and then this can be properly dealt with.

**Comment by doomspork** [comment]
Thanks @maxnordlund 👍
