### ISSUE TITLE
JWT doesn't include JSON

### ISSUE THREAD

**Issue by Licenser** [ueberauth/guardian#301]
I'm a bit baffled, probably because I've no idea what I'm doing, but it seems the JWT that gets generated by guarding is missing the J part of JWT. Sneaky as I am, I copied the header and put it in https://jwt.io/ to see what the payload is, and it seems like it's not JSON at all -.-

While the encoding isn't much of a problem when it comes to handling things inside elixir it gets problematic when trying to extract data from the JWT in the browser.

I looked at the docs and code and could not find any mention of where / if it is possible to change the payload encoding.

The JTW that I saw is:

```
SFMyNTY.g3QAAAADbQAAAAtfY3NyZl90b2tlbm0AAAAYTEptc0Q2eU5lNTNkK213TWhqQll4Zz09bQAAABBndWFyZGlhbl9kZWZhdWx0bQAAAVxleUpoYkdjaU9pSklVelV4TWlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKaGRXUWlPaUpWYzJWeU9qRWlMQ0psZUhBaU9qRTBPVGN3T0RrM056UXNJbWxoZENJNk1UUTVORFE1TnpjM05Dd2lhWE56SWpvaVQzSm5kRzl2YkVSaUxtUmxkaUlzSW1wMGFTSTZJbVk0WlRSbVltWXpMVGN6T1RVdE5EQTJNaTFoWWpCakxURTNNR1F4WlRFd09EZzRNQ0lzSW5CbGJTSTZleUprWldaaGRXeDBJam90TVgwc0luTjFZaUk2SWxWelpYSTZNU0lzSW5SNWNDSTZJbUZqWTJWemN5SjkuQ0ZRWjhLUXl6TVJlclF5c0RFSGF4X1ZKTFlnX3p5dGsxZ25OVGJqSXZQVExwZG5nREtyNG5IeVZ1RUd0VnhDTnBVdnpIYkFYWFYyRlFnYjh2R0RSQ2dtAAAADXBob2VuaXhfZmxhc2h0AAAAAW0AAAAEaW5mb20AAAASU2lnbmVkIGluIGFzIGhlaW56.gaae89vO_X-cZisl2rnj98zWQH1ro-jJkr3suC-ohnE
```

**Comment by scrogson** [comment]
Hi @Licenser, can you provide the configuration you're using?

**Comment by scrogson** [comment]
Looking at the value you included in this issue, it appears that the payload looks like this:

```
tm_csrf_tokenmLJmsD6yNe53d+mwMhjBYxg==mguardian_defaultm\eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjEiLCJleHAiOjE0OTcwODk3NzQsImlhdCI6MTQ5NDQ5Nzc3NCwiaXNzIjoiT3JndG9vbERiLmRldiIsImp0aSI6ImY4ZTRmYmYzLTczOTUtNDA2Mi1hYjBjLTE3MGQxZTEwODg4MCIsInBlbSI6eyJkZWZhdWx0IjotMX0sInN1YiI6IlVzZXI6MSIsInR5cCI6ImFjY2VzcyJ9.CFQZ8KQyzMRerQysDEHax_VJLYg_zytk1gnNTbjIvPTLpdngDKr4nHyVuEGtVxCNpUvzHbAXXV2FQgb8vGDRCgm
phoenix_flashtminfomSigned in as heinz
```

It looks like the JWT is being encoded inside the payload.

```
eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjEiLCJleHAiOjE0OTcwODk3NzQsImlhdCI6MTQ5NDQ5Nzc3NCwiaXNzIjoiT3JndG9vbERiLmRldiIsImp0aSI6ImY4ZTRmYmYzLTczOTUtNDA2Mi1hYjBjLTE3MGQxZTEwODg4MCIsInBlbSI6eyJkZWZhdWx0IjotMX0sInN1YiI6IlVzZXI6MSIsInR5cCI6ImFjY2VzcyJ9.CFQZ8KQyzMRerQysDEHax_VJLYg_zytk1gnNTbjIvPTLpdngDKr4nHyVuEGtVxCNpUvzHbAXXV2FQgb8vGDRCgm
```

Putting that into jwt.io shows this:

Header:
```json
{
  "alg": "HS512",
  "typ": "JWT"
}
```

Payload:
```json
{
  "aud": "User:1",
  "exp": 1497089774,
  "iat": 1494497774,
  "iss": "OrgtoolDb.dev",
  "jti": "f8e4fbf3-7395-4062-ab0c-170d1e108880",
  "pem": {
    "default": -1
  },
  "sub": "User:1",
  "typ": "access"
}
```

**Comment by Licenser** [comment]
Ohhhh! you are right it's a JWT inside a EWT? The outside seems to be an erlang term, I suspose that's not a guardian thing but something phoenix adds around it. I guess  I'll close this and dig around in phoenix :) sorry for the wrong place for the bug, I thought the outer wrapper is the guardian one.

PS: thanks for the great library!
