### ISSUE TITLE
Request support for Phoenix 1.3 release candidate

### ISSUE THREAD

**Issue by atom-r** [ueberauth/guardian#317]
Not sure if this is worth opening as an issue. Support for 1.3 would be great. Or some kind of a temporary workaround.

**Comment by doomspork** [comment]
@atom-r this has been covered numerous times already.  Please look at the many existing issues for 1.3 compatibility:

https://github.com/ueberauth/guardian/issues/273
https://github.com/ueberauth/guardian/issues/274
https://github.com/ueberauth/guardian/issues/276
https://github.com/ueberauth/guardian/issues/277
https://github.com/ueberauth/guardian/issues/279
https://github.com/ueberauth/guardian/issues/288
