### ISSUE TITLE
Guardian.Permissions.all? acts like or not and

### ISSUE THREAD

**Issue by Licenser** [ueberauth/guardian#329]
It seams that the `all?` function acts like the `any?` function given the following code:

```elixir
    perms = Guardian.Permissions.from_claims(claims, :player)
    can_update = Guardian.Permissions.all?(perms, [:update], :player)
    can_read = Guardian.Permissions.all?(perms, [:read], :player)
    read_and_update = Guardian.Permissions.all?(perms, [:read, :update], :player)
    :io.format("can_read: ~p~n", [can_read])
    :io.format("can_update: ~p~n", [can_update])
    :io.format("read_and_update: ~p~n", [read_and_update])
```

produces the following output:
```
can_read: true
can_update: false
read_and_update: true
```

with the config:
```elixir
  permissions: %{
    #            1      2        4      8        16       32       64
    player:     [:read, :create, :edit, :delete],
  }
```

**Comment by hassox** [comment]
Hey @licenser can you please show the raw perms from your example? At first glance I'd say it's becausewhen you're checking the permissions you're using "update" but in your config you're using edit.

**Comment by hassox** [comment]
Going to assume it was the mis-named permission name. Please let me know if that wasn't it.

**Comment by Licenser** [comment]
Oh damn sorry for getting back so late, GH only told me there was a reply today. Yea you're right it's a typo -.- damn me.

That said, I wonder if would be better to error/crash on unknown permissions. Given it's security it feels to like like airing on the side of caution. would be better? I mean 'unknown permission == always true' seems odd.
