### ISSUE TITLE
Broken __using__ in Phoenix Socket integration

### ISSUE THREAD

**Issue by iJackUA** [ueberauth/guardian#337]
Hi, it looks like this change
https://github.com/ueberauth/guardian/commit/fa041f08c6a241b2707dae77c504e7e5c1b411e0#diff-9b0cf1043709cd1ce128d2d56e3b1c22L57
breaks automatic usage of `use Guardian.Phoenix.Socket`

```
warning: variable "params" does not exist and is being expanded to "params()", please use parentheses to remove the ambiguity or change the variable name
  lib/***/web/channels/user_socket.ex:3

== Compilation error on file lib/***/web/channels/user_socket.ex ==
** (CompileError) lib/***/web/channels/user_socket.ex:3: undefined function params/0
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

I have `use Guardian.Phoenix.Socket` at `user_socket.ex:3` and as I understand it fails on evaluation of `__using__`. 
Also I can not eliminate evaluation of `__using__` even if I override `def connect` with correct  `params` pass.

**Comment by jcomellas** [comment]
This is happening because within the `Guardian.Phoenix.Socket__using__/1` function the `params` variable is used as an argument to `sign_in/4` without it being bound to anything. The commit mentioned in the issue removed the binding.

PR #338 fixes the problem.
