### ISSUE TITLE
Not an issue, its a question

### ISSUE THREAD

**Issue by ltenzil** [ueberauth/guardian#340]
Hi, I am a rails guys, just started exploring phoenix. Is it(guardian) is more like devise for rails. Does it support  mainly sub domain logins and other features supported by devise. If its not, please tell me which does. Please help me out here. Thanks in advance

**Comment by hassox** [comment]
Hi @ltenzil 

The closest library in Ruby to guardian is Warden (devise is built on top of Warden). I haven't been tracking it closely but the closest lib I can think of to devise is sentinal. https://hex.pm/packages/sentinel

**Comment by ltenzil** [comment]
Hi @hassox 
Thanks for replying ASAP. I am at 0th level in phoenix. I have just started reading the book. Is there any tutorial series, which you recommend. Slack for beginners, forum i can join specific to phoenix. 
Anything will be helpful. Once again thank you

**Comment by hassox** [comment]
The slack for elixir-lang is good. Lots of folks in there that are willing to help. 

#phoenix or #general are good all round channels. There is also an #ueberauth channel for things related to Guardian and Ueberauth.

The programming Phoenix book by Chris is a great resource to get up and running especially if you're coming from a rails background. https://pragprog.com/book/phoenix/programming-phoenix

Welcome to Elixir!

**Comment by ltenzil** [comment]
programming-phoenix is the book i am reading. Thank You So Much spending time and answering all my queries. Will join you guys. Bye Have a great day! :)
