### ISSUE TITLE
mix deps.get error

### ISSUE THREAD

**Issue by quytang** [ueberauth/guardian#341]
Guardian doesn't work with the newest version of Phoenix

```
defp deps do
    [{:phoenix, "~> 1.3.0-rc"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.2"},
     {:postgrex, ">= 0.0.0"},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:comeonin, "~> 3.0"},
     {:guardian, "~> 0.14"}]
  end
```

$ mix deps.get
```
Failed to use "phoenix" (version 1.3.0-rc.2) because
  guardian (versions 0.14.0 to 0.14.2) requires ~> 1.2.0
  mix.lock specifies 1.3.0-rc.2
```

**Comment by hassox** [comment]
Hey @quytang

Sorry about the issue :( this will be resolved in the next release. For now you can add the "override: true" option to your phoenix deps to get you going.

**Comment by quytang** [comment]
tks @hassox

**Comment by hassox** [comment]
I've put up a PR for this at https://github.com/ueberauth/guardian/pull/343

**Comment by milkcocoa** [comment]
Hi @hassox

Do you have any plan when this fix is released?
