### ISSUE TITLE
How can you obtain the base64 version of the Guardian secret_key

### ISSUE THREAD

**Issue by phtrivier** [ueberauth/guardian#349]
I'm configuring guardian with a binary as a secret key:

  > mix phx.gen.secret
  yUj59VqsZRLELkqyO21AHk0ztcAfLKeMUB67KpPPZSRttTy1zqF4y9XYSbZGjXVx

When I generate a token and paste it in an online decoder like https://jwt.io/ , the token gets decoded fine, but using the default "secret", the signature is invalid (as expected.)

However, I can not seem to pass the proper secret to the decoder. What should it be ? 

* the string itself ? As I understand it, JOSE parses it as an "octet sequence" (though I'm not sure what this means)
* the base64 version of this string ? I tried that, and it does not seem to work
* or is there a way to convert from "oct" to a base64 string ?

**Comment by hassox** [comment]
I'm not sure. I've never tried to paste my. Secret I to an online decoder :/

**Comment by doomspork** [comment]
@phtrivier could you share more of your configuration?  I took the key you provided above, threw it into an old project of mine (https://github.com/doomspork/watercooler), generated a JWT, and was able to verify it via jwt.io:

```elixir
iex> {:ok, jwt, full_claims} = Guardian.encode_and_sign[error] Postgrex.Protocol 
{:ok,
 "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjEiLCJleHAiOjE1MDEyODg1MDUsImlhdCI6MTQ5ODY5NjUwNSwiaXNzIjoiV2F0ZXJjb29sZXIiLCJqdGkiOiI2YTYxY2RhNC01NDRiLTQ3YTMtYTRhMS0yMDRkYzVhMjk2YmQiLCJwZW0iOnt9LCJzdWIiOiJVc2VyOjEiLCJ0eXAiOiJhY2Nlc3MifQ.V0ZWIJdisREd9kB5g1GahwVZ4S9RdglucCz7b31sd87MGkhz-i7-X-MdXn2cWxxFw9I2v1AKNgx-07LJUYCvVg",
 %{"aud" => "User:1", "exp" => 1501288505, "iat" => 1498696505,
   "iss" => "Watercooler", "jti" => "6a61cda4-544b-47a3-a4a1-204dc5a296bd",
   "pem" => %{}, "sub" => "User:1", "typ" => "access"}}
```

![image](https://user-images.githubusercontent.com/73386/27666425-cd63ec76-5c30-11e7-9731-7c815c30362e.png)

Double check that you're not adding whitespace to the secret by mistake.
