### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by burley1** [ueberauth/guardian#353]
Now guardian conflicts with new version of phoenix:
`
Failed to use "phoenix" (versions 1.3.0-rc.0 to 1.3.0-rc.2) because
  deps/guardian/mix.exs requires ~> 1.2 and < 1.4.0 *
  mix.exs specifies ~> 1.3.0-rc

`

**Comment by g33kidd** [comment]
You can just add `override: true` to your phoenix dependency. 

`{:phoenix, "~> 1.3.0-rc", override: true}`

You may also want to look at #317 for a list of issues regarding 1.3.
