### ISSUE TITLE
Header auth works without Bearer specification

### ISSUE THREAD

**Issue by TheAncientGoat** [ueberauth/guardian#357]
Ran into a strange issue today, while authenticating my api - VerifyHeader did not work when specifying ```authorization: Bearer {token}```, but did work when passed without the authorization schema (Bearer), ie. ```authorization: {token}```

Pretty sure this isn't the intended behaviour?

Full pipeline follows:

```
  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
    plug MyApp.Auth.CurrentUser
  end

  pipeline :api_login_required do
    plug Guardian.Plug.EnsureAuthenticated,
      handler: MyApp.Auth.GuardianApiErrorHandler
  end

```

**Comment by doomspork** [comment]
Howdy @TheAncientGoat, this is the intended functionality.  If you wish to use the bearer realm you need to update your `VerifyHeader` plug to pass in opts:

```elixir
plug Guardian.Plug.VerifyHeader, realm: "Bearer"
```

In the upcoming version of Guardian (v1), this will be the default. 👍

**Comment by TheAncientGoat** [comment]
Thanks for the quick reply - would it be helpful if I made a pull request mentioning that in the Readme? Took me a while to figure out

**Comment by doomspork** [comment]
@TheAncientGoat sure!  We're hoping to release v1 soon and that will make this a default but in the mean time a comment in the README is a good idea 👍
