### ISSUE TITLE
v1 use Guardian not creating plug functions

### ISSUE THREAD

**Issue by plamb** [ueberauth/guardian#363]
I'm trying to do a bit of testing with the v1 branch. After a bit of trial and error I figured out that adding the Plug functions in lib/guardian.ex:303 isn't working after it checks to see if plug is loaded.

This is Phoenix 1.3 from master, with Plug 1.4.2 and Elixir 1.5.0 and Erlang 19.3.

```
iex(2)> Code.ensure_loaded?(Plug)
true
iex(3)> SearchSite.Web.Auth.Guardian.__info__(:functions)
[after_encode_and_sign: 4, after_sign_in: 5, before_sign_out: 3,
 build_claims: 3, config: 0, config: 1, config: 2, decode_and_verify: 1,
 decode_and_verify: 2, decode_and_verify: 3, default_token_type: 0,
 encode_and_sign: 1, encode_and_sign: 2, encode_and_sign: 3, exchange: 3,
 exchange: 4, on_exchange: 3, on_refresh: 3, on_revoke: 3, on_verify: 3,
 peek: 1, refresh: 1, refresh: 2, resource_from_claims: 1,
 resource_from_token: 1, resource_from_token: 2, resource_from_token: 3,
 revoke: 1, revoke: 2, subject_for_token: 2, verify_claims: 2]
```
None of the plug related functions like sign_in and sign_out are there. My wild guess is that ```Code.ensure_loaded?(Plug)``` is false at compile time.

**Comment by doomspork** [comment]
Thanks for the report @plamb!  I'll take a peek this week but in the mean time we'll see if @hassox has any thoughts.

**Comment by hassox** [comment]
@plamb I'm on my phone so cannot say for sure but I believe that plug functions are put onto a nested Plug module. I.e. SearchSite.Web.Auth.Guardian.Plug

**Comment by plamb** [comment]
@hassox you are right, I really should have noticed that. It's right there in the v1 read me too.

**Comment by hassox** [comment]
Glad you got it sorted :)
