### ISSUE TITLE
v1 pipeline config

### ISSUE THREAD

**Issue by plamb** [ueberauth/guardian#367]
This may be me not reading the documentation correctly again. And I apologize for not having the time to write a better issue.

When I defined a pipeline I created a module that's basically a copy and paste from the readme:
```
defmodule SearchSite.Web.Auth.AccessPipeline do
  use Guardian.Plug.Pipeline, otp_app: :search_site_web

  plug Guardian.Plug.VerifySession#, claims: %{"typ" => "access"}
  plug Guardian.Plug.VerifyHeader#, claims: %{"typ" => "access"}
  plug Guardian.Plug.EnsureAuthenticated
  plug Guardian.Plug.LoadResource, ensure: true
end
```
Then I added the config:
```
config :search_site_web, SearchSite.Web.Auth.AccessPipeline,
  module: SearchSiteWeb.Auth.Guardian,
  error_handler: SearchSite.Web.Auth.ErrorHandler
```
Again basically a copy/paste of the readme.

But I got all sort of really bizarre stack traces that I finally tracked down to an undefined method. So I changed the pipeline module to:
```
defmodule SearchSite.Web.Auth.AccessPipeline do
  use Guardian.Plug.Pipeline, otp_app: :search_site_web,
    module: SearchSite.Web.Auth.Guardian,
    error_handler: SearchSite.Web.Auth.ErrorHandler

  plug Guardian.Plug.VerifySession#, claims: %{"typ" => "access"}
  plug Guardian.Plug.VerifyHeader#, claims: %{"typ" => "access"}
  plug Guardian.Plug.EnsureAuthenticated
  plug Guardian.Plug.LoadResource, ensure: true
end
```
Which includes the module and error handler for the use statement. And things work very nicely without any errors. So I'm thinking that something isn't getting picked up from the config correct.

**Comment by scrogson** [comment]
@plamb thanks for reporting this. We'll take a look today and make sure it's working as expected.

**Comment by scrogson** [comment]
@plamb, I've created a new app and attempted to replicate you issue but I was not able to. I know it's been awhile since you've reported this issue, but do you think you might be able to produce the  stack trace you encountered?

**Comment by scrogson** [comment]
@plamb feel free to re-open if you are able to reproduce.

**Comment by plamb** [comment]
Thanks for looking at it. I'm already on the road heading to ElixircConf. There's also been a large amount of churn in my app since then too. If it comes back up, I'll let you know.
