### ISSUE TITLE
Guardian.Permissions.Bitwise - "at least" the permission

### ISSUE THREAD

**Issue by oskar1233** [ueberauth/guardian#392]
When plugging `Guardian.Permissions.Bitwise` should `ensure` and `one_of` check for permission map to be identical or contain _at least_ specified permissions?

Now it behaves the first way - when I `plug Guardian.Permissions.Bitwise, ensure: %{superuser: [:mod]}` the permissions can't be higher, e. g. `MyApp.Guardian.encode_and_sign(user, %{}, permissions: %{superuser: [:mod, :read]})` will cause `{:unauthorized, :unauthorized}`.

_In my opinion_ it's unwanted behaviour. I suspect to `plug Guardian.Permissions.Bitwise, ensure: %{superuser: [:mod]}` and  `plug Guardian.Permissions.Bitwise, ensure: %{superuser: [:read]}` to authorize positively when I specify `permissions: %{superuser: [:mod, :read]}`.

Thanks for your attention & regards.

**Comment by doomspork** [comment]
@oskar1233 do you have some example code we could look at?

**Comment by hassox** [comment]
Agreed this should be at least. @oskar1233 do you have an example setup that shows this behaviour?

**Comment by hassox** [comment]
I found the issue I believe. @oskar1233 can you confirm that this fixes the issue for you?

https://github.com/ueberauth/guardian/pull/394

**Comment by oskar1233** [comment]
@hassox It does - thank you very much. :ship:

**Comment by hassox** [comment]
Great! It's merged. We'll cur a release soon
