### ISSUE TITLE
How do I redirect to a sign in page?

### ISSUE THREAD

**Issue by mitkins** [ueberauth/guardian#398]
I'm upgrading my app to version 1. I've setup the following pipeline to prevent unauthenticated users from accessing particular pages:

``` Elixir
defmodule Zoinks.Guardian.AuthPipeline do
  @claims %{typ: "access"}

  use Guardian.Plug.Pipeline,
    otp_app: :zoinks,
    module: Zoinks.Guardian,
    error_handler: Zoinks.Guardian.AuthErrorHandler

  plug Guardian.Plug.VerifySession, claims: @claims
  plug Guardian.Plug.EnsureAuthenticated
  plug Guardian.Plug.LoadResource, ensure: true
end
```

And here's my error handler:

``` Elixir
defmodule Zoinks.Guardian.AuthErrorHandler do
  import Plug.Conn

  def auth_error(conn, {type, _reason}, _opts) do
    body = Poison.encode!(%{message: to_string(type)})
    send_resp(conn, 401, body)
  end
end
```

In the past (0.14) I had an `unauthenticated` function handler in the Controller - which allowed me to use `conn.put_flash` and `conn.redirect`. With the new error handler, how do I redirect to a login page?

**Comment by oskar1233** [comment]
I think you can create module like `AuthErrorController`, which will be either Phoenix's controller and error handler in terms of Guardian.

I would add `use ZoinksWeb, :controller` to the module, then think about naming and adding it into `Web` namespace.

**Comment by hassox** [comment]
You can still use a function in the controller to handle errors. Keep the pipeline you have in place and in your controller set a different error handler.

```elixir
defmodule MyAppWeb.MyController do
  use MyAppWeb, :controller

  plug Guardian.Plug.Pipeline, error_handler: __MODULE__

  # snip

  def auth_error(conn, {type, reason}, _opts) do
    do_stuff(conn)
  end
end
```

**Comment by mitkins** [comment]
So I could create an `AuthErrorController` like @oskar1233 suggests and set that in my controller (as pointed out by @hassox) while still having `Zoinks.Guardian.AuthErrorHandler` as the global handler?

**Comment by hassox** [comment]
Yes you could do it that way. When you use the pipeline plug you setting the error handler for all downstream plugs. You can change it out as often as you need to.

**Comment by mitkins** [comment]
Cool. Thanks!
