### ISSUE TITLE
Using halt on auth_error

### ISSUE THREAD

**Issue by uzarubin** [ueberauth/guardian#401]
I would always get `(Plug.Conn.AlreadySentError) the response was already sent` when I tried to use the example `auth_error` as the `error_handler` inside my pipeline. 

It wasn't until I added `|> halt` that the issue was fixed. See below for an example. 

```elixir
defmodule MyApp.AuthErrorHandler do
  import Plug.Conn

  def auth_error(conn, {type, reason}, _opts) do
    body = Poison.encode!(%{message: to_string(type)})
    # send_resp(conn, 401, body)  <--- This line causes the error

    send_resp(conn, 401, body) |> halt # this makes the error go away  
  end
end
```

I was wondering if this is something that I messed up in my own configuration, or there was a forgotten `halt` in the documentation?

**Comment by oskar1233** [comment]
I suggest pasting your configuration as well.

Answering you question: `halt` shouldn't be needed here, docs aren't wrong on this.

**Comment by uzarubin** [comment]
@oskar1233 I was actually following your example on some of these things.  Here is the config from my project:
``` 
defmodule Wire.Guardian.Pipelines.JsonAuth do
  use Guardian.Plug.Pipeline, otp_app: :wire,
                              module: Wire.Guardian,
                              error_handler: Wire.Guardian.ErrorHandler

  plug Guardian.Plug.VerifyHeader, realm: "Bearer"
  plug Guardian.Plug.EnsureAuthenticated
  plug Guardian.Plug.LoadResource, allow_blank: false
end
```

And here is my `router` file:

```
pipeline :authorize_admin do
    plug Wire.Guardian.Pipelines.JsonAuth
  end

 scope "/admin", WireWeb do
    pipe_through :authorize_admin
    post "/invite-tokens/expire", BusinessAdmin.InvitesController, :expire
  end
```

**Comment by uzarubin** [comment]
Going to go ahead and close this.

**Comment by hauptbenutzer** [comment]
I'm sorry to say, this does prevent me from using guardian 1.x with absinthe (or any such API-framework, I would imagine). The problem here is, that in a GraphQL Query some requested fields might require authentication/authorization before resolving, while some don't. To make the distinction, the plug pipeline has to first reach the Absinthe plug. This, due to the `halt` in the Guardian plugs, cannot happen at the moment. 

In fact, there is no way (as far as I can tell) to use the here-mentioned Guardian plugs, and still reach the app logic (absinthe or anything else, really) without manually calling it in the ErrorHandler module.
Making the `halt` a configurable behaviour, would probably alleviate this issue.

**Comment by ratbag98** [comment]
I've reached this thread probably for the same reason as @hauptbenutzer - in the middle of upgrading my app to use Guardian 1.x and I'm crashing out of my auth error handler if the user isn't logged in.

**Comment by mpoeter** [comment]
Same problem here! Please let the user decide whether to halt or not.

**Comment by Apelsinka223** [comment]
@hauptbenutzer @ratbag98 @mpoeter have you solved this problem somehow?

**Comment by ratbag98** [comment]
Sorry @Apelsinka223 , I dropped Guardian the day after posting my “me too” and coded my own very simple system that does what we need and no more.

**Comment by Apelsinka223** [comment]
@doomspork is there any chance that `halt` would become configurable?

**Comment by mpoeter** [comment]
@Apelsinka223 I simply created my own VerifyHeader module by copying the code from the Guarding module and removing the halt call.

**Comment by hauptbenutzer** [comment]
@Apelsinka223 We simply built a wrapper module that would unhalt the connection: https://gist.github.com/hauptbenutzer/bcc528c622317aabf0b8c5ee1890c536 Not pretty, but it does the job.

**Comment by Apelsinka223** [comment]
@hauptbenutzer looks like best solution, thank you!

**Comment by DmitryKK** [comment]
I have same problem. Why was the issue closed?

**Comment by yordis** [comment]
@DmitryKK the person who opened the issue closed it 🤷‍♂ 

I will suggest to open a new issue and share your particular situation.

**Comment by oskar1233** [comment]
@DmitryKK @yordis Configurable halt has been merged in https://github.com/ueberauth/guardian/pull/617.
