### ISSUE TITLE
(Protocol.UndefinedError) When using MyApp.Guardian.Plug.sign_in on ~> 1.0-beta

### ISSUE THREAD

**Issue by Euklidian-Space** [ueberauth/guardian#411]
I am attempting to use Plug.sign_in passing in a user struct returned from an ecto query and I am getting the following error output 

[error] #PID<0.562.0> running VoterWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /api/sessions
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for :access. This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Postgrex.Stream, Range,Stream
        (elixir) /private/tmp/elixir-20170929-51947-wgj4qu/elixir-1.5.2/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) /private/tmp/elixir-20170929-51947-wgj4qu/elixir-1.5.2/lib/elixir/lib/enum.ex:116: Enumerable.reduce/3
        (elixir) lib/enum.ex:1847: Enum.reverse/1
        (elixir) lib/enum.ex:2596: Enum.to_list/1
        (elixir) lib/map.ex:174: Map.new_from_enum/1
        (guardian) lib/guardian.ex:541: Guardian.encode_and_sign/4
        (guardian) lib/guardian/plug.ex:179: Guardian.Plug.sign_in/5
        lib/voter_web/controllers/session_controller.ex:34: VoterWeb.SessionController.create/2
        lib/voter_web/controllers/session_controller.ex:1: VoterWeb.SessionController.action/2
        lib/voter_web/controllers/session_controller.ex:1: VoterWeb.SessionController.phoenix_controller_pipeline/2
        (voter) lib/voter_web/endpoint.ex:1: VoterWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (voter) lib/voter_web/endpoint.ex:1: VoterWeb.Endpoint.plug_builder_call/2
        (voter) lib/plug/debugger.ex:99: VoterWeb.Endpoint."call (overridable 3)"/2
        (voter) lib/voter_web/endpoint.ex:1: VoterWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) 

Here is the controller action I have defined

```elixir
def create(conn, %{"user" => %{"credential" => %{"email" => email, "password_hash" => password}}}) do
    with { :ok, user } <- Accounts.authenticate_by_email_password(email, password) do

      new_conn = conn |> Voter.Guardian.Plug.sign_in(user, :access)
      jwt = new_conn |> Voter.Guardian.Plug.current_token



      new_conn
      |> put_status(:created)
      |> render("show.json", user: user, jwt: jwt)
    end
  end
```

and here is my function the does the Repo query
```elixir
def authenticate_by_email_password(email, password) do
    _email = String.downcase email

    query = 
      from u in User,
      join: c in assoc(u, :credential),
      where: c.email == ^_email,
      preload: [credential: c]

    user = Repo.one query

    case check_pw(user, password) do
      true -> { :ok, user }

      _otherwise -> { :error, :unauthorized }
    end
  end
```
 
Not too sure where to go from here.

**Comment by doomspork** [comment]
@Euklidian-Space which version of Guardian are you currently using?

**Comment by doomspork** [comment]
@Euklidian-Space if you're using Guardian 1.0 you'll need to change up the params to sign_in.  Try something like this:

```elixir
Voter.Guardian.Plug.sign_in(conn, user, %{}, token_type: "access")
```

**Comment by scrogson** [comment]
Based on the example code above (`Voter.Guardian.Plug.sign_in`), it looks like @Euklidian-Space is using `1.0`
