### ISSUE TITLE
sign_out clears all messages added by put_flash

### ISSUE THREAD

**Issue by vjorjo** [ueberauth/guardian#412]
I have this code:

``` elixir
@logout_msg "Signed out successfully!"

def delete(conn, _params) do
   conn
   |> Guardian.Plug.sign_out()
   |> put_flash(:info, @logout_msg)
   |> redirect(to: page_path(conn, :index))
end
```
the problem is that sign_out drops the entire session and consequently it deletes flash messages.
However a previous version I had used in another project didn't have this side effect.

Is there any solution for this?

**Comment by doomspork** [comment]
Sounds like a bug in 1.0, thanks for the report!
