### ISSUE TITLE
Fix Guardian compilation when Plug is not being use

### ISSUE THREAD

**Issue by yordis** [ueberauth/guardian#415]
https://github.com/ueberauth/guardian/blob/708f924806995c749c6c27c3c93dab76fc212bde/lib/guardian/permissions/bitwise.ex#L371  for some reason that line is not actually doing what we expect and the compilation of Guardian fails if there is no `Plug` module

`V1` related

**Comment by Hanspagh** [comment]
So its seems like` Code.ensure_loaded` only work on module level. I propose to move the permission plug to Guardian.Plug.Permission, this however is a breaking change. What do you think about this?

**Comment by Hanspagh** [comment]
Fixed by #404
