### ISSUE TITLE
(RuntimeError) `module` not set in Guardian pipeline

### ISSUE THREAD

**Issue by beno** [ueberauth/guardian#420]
I just moved from 0.14 to 1.0 beta, followed the guides and docs as best I could but I keep running into the above error. I haven't found any mention of a `module` config or where I am supposed to put it, probably some missing router setup ( I am using a fairly basic Phoenix MVC app)? Please advise and if necessary update the docs.

**Comment by Hanspagh** [comment]
Sounds like your are missing setting a module for your pipeline, take a look at this https://github.com/ueberauth/guardian#create-a-custom-pipeline, if you have already done this, could you provide a code sample or a more detailed error message?

**Comment by beno** [comment]
It turns out I needed to add 

    plug Guardian.Plug.Pipeline, module: App.Guardian, error_handler: App.Web.SessionController

to my 0.14 pipelines.

**Comment by beno** [comment]
It turns out I needed to add 

    plug Guardian.Plug.Pipeline, module: App.Guardian, error_handler: App.Web.SessionController

to my 0.14 pipelines.
