### ISSUE TITLE
Guardian.revoke(token) method raises error

### ISSUE THREAD

**Issue by SofaKing18** [ueberauth/guardian#435]
In calling method Guardian.revoke(token) getting error below:

![image](https://user-images.githubusercontent.com/15660128/34160130-be3d9104-e4dc-11e7-9640-502f01d8839e.png)

Seems like `mod.peek(token) ` should be replaced to `token_mod.peek(token)`

But when i did this, got another error:
![image](https://user-images.githubusercontent.com/15660128/34160360-b0919496-e4dd-11e7-81c3-d2dfda565d4e.png)

I'm using Elixir 1.5.2

**Comment by yordis** [comment]
Fixed by https://github.com/ueberauth/guardian/pull/430 

@ueberauth/core could somebody release it if it nos released yet.

**Comment by yordis** [comment]
@hassox Do you think is possible to have some patch release so people dont keep getting into this error?

**Comment by doomspork** [comment]
@yordis and @SofaKing18 v1.0.1 has been released 👍
