### ISSUE TITLE
Migration guide

### ISSUE THREAD

**Issue by atomkirk** [ueberauth/guardian#437]
Can you provide a quick migration guide from <1 to 1?

Maybe in the wiki?

**Comment by joshuataylor** [comment]
https://github.com/ueberauth/guardian/blob/master/upgrade_guides/0.14.to.1.0.md

And the CHANGELOG as well, though it's missing removed functions.

**Comment by yordis** [comment]
@joshuataylor thank you for pointing it out.

@atomkirk if you have any feedback from the migration let us know.

**Comment by joshuataylor** [comment]
I'm in the middle of a migration from 0.14 to 1.0, and the guide seems great so far :+1:
