### ISSUE TITLE
Issues refreshing jwt

### ISSUE THREAD

**Issue by jstoeffler** [ueberauth/guardian#439]
Hello. I'm new with elixir, so sorry if this is a noob question.
I managed to register users and get a jwt. However I have some problems trying to refresh it.

Here's my code:

	  def refresh(conn, _params) do
	    user = Cryptohexa.Guardian.Plug.current_resource(conn)
	    jwt = Cryptohexa.Guardian.Plug.current_token(conn)
	    Logger.info "Previous jwt:"
	    Logger.info jwt

	    case Cryptohexa.Guardian.refresh(jwt) do
	      {:ok, new_jwt, _new_claims} ->
	        Logger.info "New jwt"
	        Logger.info new_jwt
                # ... rest of the code

And here's the output :

	[info] Previous jwt:
	[info] eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJjcnlwdG9oZXhhIiwiZXhwIjoxNTE3MjM3MTA3LCJpYXQiOjE1MTQ4MTc5MDcsImlzcyI6ImNyeXB0b2hleGEiLCJqdGkiOiI4MmMzMjM5Yy1hODA5LTRlNDctYTRjYi00YTA0YmQ2MWRiYWMiLCJuYmYiOjE1MTQ4MTc5MDYsInN1YiI6IjEyIiwidHlwIjoiYWNjZXNzIn0.YQz0mjlOiOi1xt3bJwV5T9Uk4K7vaAjMHMvOP_GF1k6ZOtP4n5HbLterelgj202gF2N2wT9vNMMuyME0ImUOow
	[info] New jwt
	[info] Sent 500 in 158ms
	[error] #PID<0.426.0> running Cryptohexa.Endpoint terminated
	Server: localhost:4000 (http)
	Request: POST /api/sessions/refresh
	** (exit) an exception was raised:
	    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJjcnlwdG9oZXhhIiwiZXhwIjoxNTE3MjM3MTA3LCJpYXQiOjE1MTQ4MTc5MDcsImlzcyI6ImNyeXB0b2hleGEiLCJqdGkiOiI4MmMzMjM5Yy1hODA5LTRlNDctYTRjYi00YTA0YmQ2MWRiYWMiLCJuYmYiOjE1MTQ4MTc5MDYsInN1YiI6IjEyIiwidHlwIjoiYWNjZXNzIn0.YQz0mjlOiOi1xt3bJwV5T9Uk4K7vaAjMHMvOP_GF1k6ZOtP4n5HbLterelgj202gF2N2wT9vNMMuyME0ImUOow", %{"aud" => "cryptohexa", "exp" => 1517237107, "iat" => 1514817907, "iss" => "cryptohexa", "jti" => "82c3239c-a809-4e47-a4cb-4a04bd61dbac", "nbf" => 1514817906, "sub" => "12", "typ" => "access"}}. This protocol is implemented for: Atom, BitString, Date, DateTime, Decimal, Ecto.Date, Ecto.DateTime, Ecto.Time, Float, Integer, List, NaiveDateTime, Postgrex.Copy, Postgrex.Query, Postgrex.Stream, Time, URI, Version, Version.Requirement

So there are two things that I don't understand here:

1. The new_jwt is a tuple and not a string like the one created during registration
2. I could take the first value of the tuple, but it's the same token and I was expecting a different "refreshed" one.

Is there something I'm missing?

Thanks for your help!

**Comment by hassox** [comment]
Hi. Not sure if the code you pasted is the code you're running. You're logging test_jwt but it should be new_jwt. Is that accurate?

**Comment by jstoeffler** [comment]
Yes, sorry for the confusion I updated the code.

**Comment by hassox** [comment]
Refresh has a slightly different signature than encode and sign. It returns

{:ok, {old_token, old_claims}, {new_token, new_claims}}

So your pattern match in your case would need to be

{:ok, _, {new_jwt, _}}

**Comment by jstoeffler** [comment]
Thanks, I'm not very confident with signatures in elixirs and pattern matching.

However I still get the same token after it has been refreshed, is that expected?

**Comment by jstoeffler** [comment]
Oh my bad, it's just the beginning of the token which is the same. It's different.

Thanks for your help!
