### ISSUE TITLE
Guardian.Plug.sign_out doesn't call revoke

### ISSUE THREAD

**Issue by kelostrada** [ueberauth/guardian#447]
Is it intentional that `sign_out` doesn't call revoke on tokens?

**Comment by denvaar** [comment]
From what I understand, revoke only works if you are storing the tokens somewhere, such as with [GuardianDB](https://github.com/ueberauth/guardian_db)

**Comment by tarzan** [comment]
I think I'm having similar issues. 

From the README:
```ex
# remove from session (if fetched) and revoke the token
conn = MyApp.Guardian.Plug.sign_out(conn)
```
However, revoke is indeed never called. So, that seems to be an error in the documentation.

I am trying to hook up GuardianDB and follow the instructions there. It instructs to just put the GuardianDB interface on the `on_revoke`-hook like this:
```ex
  def on_revoke(claims, token, _options) do
    with {:ok, _} <- Guardian.DB.on_revoke(claims, token) do
      {:ok, claims}
    end
  end
```

In my app I just call the `MyApp.Guardian.Plug.sign_out(conn)` and the `on_revoke` is never triggered, therefore never deleting a persisted token in the database...

@doomspork would a PR fixing this be appreciated? Or is this wanted behaviour?

**Comment by doomspork** [comment]
@tarzan please do open a PR 👍

**Comment by tarzan** [comment]
Should be solved by #458.

**Comment by mirago** [comment]
Hey guys, didn't want to open a new issue for this, but even after reading PR by @tarzan and installing guardian 1.01, the revoke callback is never called for me. I'm wondering what am I missing. Can you guys confirm it's actually being called? thanks

**Comment by doomspork** [comment]
@mirago we wanted to package up some other changes but we can cut a release with these changes 👍 

In the meantime you can do: `{:guardian, github: "ueberauth/guardian"}`

**Comment by mirago** [comment]
thanks for your reply, I will wait for the release, until then I am calling revoke manually and all works perfectly. 👍
