### ISSUE TITLE
How to pass error_handler into pipeline?

### ISSUE THREAD

**Issue by delameko** [ueberauth/guardian#449]
I'm having a bit of trouble passing a special error_handler into a pipeline, and feel like I might be missing something.

My pipeline:

```Elixir
defmodule Auth.Pipeline do
  @claims %{typ: "access"}

  use Guardian.Plug.Pipeline, otp_app: :auth,
                              module: Auth.Guardian
  plug Guardian.Plug.VerifySession, claims: @claims
  plug Guardian.Plug.VerifyHeader,  claims: @claims
  plug Guardian.Plug.EnsureAuthenticated
  plug Guardian.Plug.LoadResource,  ensure: true
end
```

And in my router:
```Elixir
  pipeline :authenticate do
    plug Auth.Pipeline, error_handler: MyApp.AuthErrorHandler
  end
```

I always get `** (RuntimeError) 'error_handler' not set in Guardian pipeline`.

If I try to add an error_handler to the pipeline (hoping it'll be overridden), it'll always use the one defined.

In the documentation it says "Once you’ve created a pipeline, you can customize it when you call it with options.", but it only show passing `module` and `key`.  Is it not possible to pass an error_handler this way?  Or is there some way of doing it I'm missing?

Thanks for any assistance.

**Comment by scrogson** [comment]
@delameko I don't think that is possible at the moment. Probably an oversight on our part. I think what you seek is definitely doable. Thanks for bringing it to our attention.

**Comment by delameko** [comment]
Thanks for the response.  I've got a workaround in place for the moment, so its not a big issue.

You folks have done a fantastic job with version 1.0.  I've just updated from 0.14 and moved all my authentication code to a separate app in my umbrella, and this has been the only issue I had.  And its only an issue for me because of the code separation, as I want my api app and web app to pass in their own respective error_handlers, but I don't want to reference Guardian directly in those apps.

**Comment by hassox** [comment]
Hey sorry I didn't see this in time.

With pipelines you can set either the module or error handler upstream. The last set one will be in effect when your pipeline executes. So for your case you could do:

```elixir
pipeline :authenticate do
  plug Guardian.Plug.Pipeline, error_handler: MyApp.AuthErrorHandler
  plug Auth.Pipeline
end
```

**Comment by delameko** [comment]
Yeah, I've sort of got that now.  Because I've got an umbrella, and auth as a separate app, I was hoping I could do:

```Elixir
pipeline :authenticate do
  plug AuthApp.Pipeline, error_handler: MyApp.AuthErrorHandler
end
```
As I didn't want to add Guardian as a dependency of MyApp.  At the moment, as a workaround, I've got:
```Elixir
pipeline :authenticate do
  plug AuthApp.plug_pipeline(), error_handler: MyApp.AuthErrorHandler
  plug AuthApp.Pipeline
end

# authapp.ex
def plug_pipeline() do
  Guardian.Plug.Pipeline
end
```
It's not ideal, it'll do for now.

**Comment by asppsa** [comment]
It's possible to override the `init` and `call` functions in `Plug.Builder`, so you can implement the desired interface like so:

```
defmodule MyApp.Pipeline do
  use Plug.Builder

  @defaults [module: MyApp.Guardian, error_handler: MyApp.Guardian.AuthErrorHandler]

  def init(opts) do
    {
      Guardian.Plug.Pipeline.init(Keyword.merge(@defaults, opts)),
      super(opts)
    }
  end

  def call(conn, {guardian_opts, opts}) do
    case Guardian.Plug.Pipeline.call(conn, guardian_opts) do
      %Plug.Conn{halted: true} = conn ->
        conn

       conn ->
         super(conn, opts)
  end

  plug(...) # etc
end
```

Perhaps the default `use Guardian.Plug.Pipeline` could be wired up using something like the above?
