### ISSUE TITLE
Unknown Units: weeks for token ttl

### ISSUE THREAD

**Issue by sebastialonso** [ueberauth/guardian#452]
I changed the ttl to the following (just to play)
~~~
# Configures Guardian
config :guardian, Guardian,
  allowed_algos: ["HS512"],
  verify_module: Guardian.JWT,
  ttl: { 52, :weeks },
~~~

And I get the following error
~~~
** (RuntimeError) Unknown Units: weeks
users_1  |         lib/guardian/claims.ex:157: Guardian.Claims.assign_exp_from_ttl/2
users_1  |         lib/guardian.ex:439: Guardian.set_ttl/1
users_1  |         lib/guardian.ex:413: Guardian.build_claims/3
users_1  |         lib/guardian.ex:72: Guardian.encode_and_sign/3
~~~

I highly presume the error has to do with my version of Guardian, which is **0.14**. By requirement, I can't change the version. Can I get away with using another time unit other than day?

Thanks!

**Comment by scrogson** [comment]
@sebastialonso is there a reason you can't use `{1, :year}` or `{365, :days}`?

**Comment by sebastialonso** [comment]
Absolutely not. I can use them. :)

It just happened that I took a look at the code and there seems to be code
for managing both the week and weeks symbol, so it was a situation I felt I
had to report. But yeah, just use the days symbol.

On 31 Jan 2018 1:39 pm, "Sonny Scroggin" <notifications@github.com> wrote:

@sebastialonso <https://github.com/sebastialonso> is there a reason you
can't use {1, :year} or {365, :days}?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ueberauth/guardian/issues/452#issuecomment-361991413>,
or mute the thread

**Comment by scrogson** [comment]
@sebastialonso I think what you may have seen is that `v1.0` supports `:week` and `:weeks` but `v0.14.x` does not.

**Comment by sebastialonso** [comment]
That may be it. Thanks.
