### ISSUE TITLE
encode_and_sign vs sign_in

### ISSUE THREAD

**Issue by denvaar** [ueberauth/guardian#457]
It seems like `sign_in` and `encode_and_sign` both set `:guardian_default_token` on `conn`. From reading the documentation I would expect `sign_in` to put the token on the `conn`, but not `encode_and_sign`. I would expect `encode_and_sign` to only place the token within `:req_headers` on `conn`.

Has this changed, or am I thinking of this incorrectly?

**Comment by hassox** [comment]
Hi @denvaar,

Not sure how `encode_and_sign` would put anything on the conn. It doesn't have access to it. Can you show the code that is resulting in this behaviour please?
