### ISSUE TITLE
Custom TTL not working as documented

### ISSUE THREAD

**Issue by zapient** [ueberauth/guardian#478]
```
# Customize the time to live (ttl) of the token
{:ok, token, claims} = MyApp.Guardian.encode_and_sign(resource, %{}, token_ttl: {1, :minute})
```

Looks like the documentation does not match the [implementation](https://github.com/ueberauth/guardian/blob/master/lib/guardian/token/jwt.ex#L414). Using `ttl` instead of `token_ttl` works as expected.

**Comment by doomspork** [comment]
@zapient a PR to correct the documentation is welcome 👍

**Comment by zapient** [comment]
Sure. Would you like the documentation to match the implementation or the other way around?

**Comment by yordis** [comment]
@zapient fix the documentation.
