### ISSUE TITLE
Token with sub is passed, but resource has gone

### ISSUE THREAD

**Issue by gmile** [ueberauth/guardian#480]
It is advised that the implementation module has these two methods:

```elixir
def resource_from_claims(%{"sub" => id}), do: {:ok, %{id: id}}
def resource_from_claims(_), do: {:error, :not_found}
```
First method covers the case when "sub" exists and points to a resource ID. Second method covers a case "sub" does not exist.

However there seem to be another case, where `sub` exists and points to a resource ID, but resource is absent (e.g. a user was deleted and is not in the DB anymore). Right now this must be handled manually:

```elixir
def resource_from_claims(%{"sub" => "Account#"user_id}) do
  case Repo.get(User, claims["sub"]) do
    nil ->
      {:error, :not_found}
    user ->
      {:ok, user}
  end
end
def resource_from_claims(_), do: {:error, :not_found}
```

Would you consider accepting a PR that adds a check for when loaded resource is `nil`, e.g. no resource was actually loaded?

**Comment by yordis** [comment]
@gmile the problem is that, this is related to your business usecase.

What happened if I am not using Ecto and the function that verify my user send me back `{:ok, user}|{:error, :not_found}`?

I don't believe Guardian should handle anything related to specific business rule (your case, Ecto).

**Comment by hassox** [comment]
@gmile what @yordis said. This is the function where you load it. If you can't find it then you should return an error.

If you're wanting to make sure that the resource was found in your plug pipeline, you should use the "LoadResource" with the "allow_blank" option omitted or set to false.
