### ISSUE TITLE
using the same conn twice returns unauthorized in tests

### ISSUE THREAD

**Issue by InteNs** [ueberauth/guardian#482]
hey,
my controller test is showing some weird behaviour:
```ex
  setup %{conn: conn} do
    user = insert(:user)
    {:ok, token, _claims} = KidseeApiWeb.Guardian.encode_and_sign(user)
    conn = put_req_header(conn, "authorization", "Bearer #{token}")
    {:ok, conn: conn }
  end

  describe "delete user" do
    test "deletes chosen user", %{conn: conn} do
      user = insert(:user)
      conn = delete conn, user_path(conn, :delete, user)
      assert response(conn, 204)

      conn = get conn, user_path(conn, :show, user)
      assert response(conn, 404)

    end
  end
```
the delete request returns 204 but the get request following this returns 401.
turning the calls around will make the get request work and the delete request fail.

any ideas as to what I'm doing wrong?

here is my pipeline:
```ex
defmodule KidseeApiWeb.Guardian.AuthPipeline do
  use Guardian.Plug.Pipeline, otp_app: :kidsee_api,
                              module: KidseeApiWeb.Guardian,
                              error_handler: KidseeApiWeb.Guardian.AuthErrorHandler

  plug Guardian.Plug.VerifyHeader
  plug Guardian.Plug.EnsureAuthenticated
end
```
```ex
defmodule KidseeApiWeb.Guardian do
  use Guardian, otp_app: :kidsee_api

  def subject_for_token(resource, _claims) do
    {:ok, to_string(resource.id)}
  end

  def resource_from_claims(claims) do
    id = claims["sub"]
    {:ok, KidseeApi.Accounts.get_user!(id) }
  end
end

```

**Comment by hassox** [comment]
If your user is deleted, how would they be able to access the show page for that deleted user?

**Comment by InteNs** [comment]
well, it's a test that checks if after deleting the  user the show page returns a 404, i fixed it buy not overriding conn for the first assert,  so:
```ex
test "deletes chosen user", %{conn: conn} do
      user = insert(:user)
      delete_conn = delete conn, user_path(conn, :delete, user)
      assert response(delete_conn, 204)

      get_conn = get conn, user_path(conn, :show, user)
      assert response(get_conn, 404)
    end
```

not sure if this is the best way to fix this but it works.

**Comment by hassox** [comment]
I see. Sorry I missed the nuance there. It's returning 401 because it's treating it as a "you're not authorized to make this request". It hasn't even got into the action to determine if a user is available because this is a protected resource (if it's there or not) and the current token was deemed to be invalid.

**Comment by InteNs** [comment]
yeah, although the same conn object was valid before (in the delete request) so something must have changed when that request was sent (not suprised by that to be honest.

the only reason why i even posted this was because this convention (using the same conn right after the request to check if it really is deleted) was generated with the standard mix generator.

**Comment by hassox** [comment]
So you're using a different user in the token than you're using to fetch? It may be that the conn is recycled by the phx test env. If you want to start with the same conditions for each request (i.e. a header has been set) rather than storing the conn into the conn variable which could be recycling it would probably be better to store the results off in a different conn struct.

i.e.

```elixir
  setup %{conn: conn} do
    user = insert(:user)
    {:ok, token, _claims} = KidseeApiWeb.Guardian.encode_and_sign(user)
    conn = put_req_header(conn, "authorization", "Bearer #{token}")
    {:ok, conn: conn }
  end

  describe "delete user" do
    test "deletes chosen user", %{conn: conn} do
      user = insert(:user)
      resp_conn = delete conn, user_path(conn, :delete, user)
      assert response(resp_conn, 204)

      resp_conn = get conn, user_path(conn, :show, user)
      assert response(resp_conn, 404)

    end
  end
```

**Comment by InteNs** [comment]
yes that's basically what I ended up doing, thanks for thinking with me, I'll close the issue.
