### ISSUE TITLE
see 'Guardian.Plug.Errors'

### ISSUE THREAD

**Issue by voger** [ueberauth/guardian#483]
In [this line](https://github.com/ueberauth/guardian/blob/7e839ba1c39aed2c303e01f804451cce0f9f924c/lib/guardian/plug/pipeline.ex#L64) the documentation mentions 
> see 'Guardian.Plug.Errors'

but there is not such module. What does it mean?

**Comment by hlhr** [comment]
Just to help out, the option is used to define a ErrorHandler-Module-Pug. There is not predefined plug in `guardian` but you can find an example [here](https://hexdocs.pm/guardian/readme.html#plug-error-handlers) or a definition under `### Error handler` in the same file.

**Comment by voger** [comment]
Thanks. I thought there was indeed somewhere a module with that name and I couldn't find it.
