### ISSUE TITLE
Why verify_claims function gets called two times?

### ISSUE THREAD

**Issue by jsangilve** [ueberauth/guardian#488]
I'm working on a `Guardian` module that implements `verify_claims` callback. I realized the function was always called two times. After having a look into Guardian's code, I realized that's indirectly called two times within `Guardian.decode_and_verify`:

1. `Guardian.Token.JWT`
https://github.com/ueberauth/guardian/blob/72df24d7e27e0a13ee7538c9d9537ae19ab60aff/lib/guardian.ex#L618
Previous call in `Guardian.decode_and_verify` leads to this first call in `Guardian.Token.JWT`:
https://github.com/ueberauth/guardian/blob/086c9e99332eecbda563b4f3dfbcce8bb91e0bb9/lib/guardian/token/jwt.ex#L324
2. Directly in `Guardian.decode_and_verify`
https://github.com/ueberauth/guardian/blob/72df24d7e27e0a13ee7538c9d9537ae19ab60aff/lib/guardian.ex#L619

So, my question is why do you call `verify_claims` callback in `Guardian.Token.JWT.verify_claims`?

**Comment by yordis** [comment]
This is interesting https://github.com/ueberauth/guardian/blob/72df24d7e27e0a13ee7538c9d9537ae19ab60aff/lib/guardian.ex#L618-L619

We are calling it there twice 🤔 

@hassox I think we do not need to call the second time, they are doing the same except that the one using `mod` could fail (everything should be calling `Guardian.token_module(mod)` before use the module)

**Comment by yordis** [comment]
@jsangilve the second function is optional. https://github.com/ueberauth/guardian/blob/72df24d7e27e0a13ee7538c9d9537ae19ab60aff/lib/guardian.ex#L259

You don't need to pass define a `verify_claims` callback on your `MyGuardian` module.

Do you define that callback?

**Comment by jsangilve** [comment]
Thanks for your reply @yordis.

Yes, as I mentioned in the original post, I'm implementing this callback in `MyGuardian` module.

Sorry, I still don't understand what's the purpose of calling it twice in the code. By default, this callback just return `{:ok, claims}`. So, even if I don't implement it in `MyGuardian` module, it's still called twice.

Wouldn't be enough just to call this function at `guardian/lib/guardian.ex`?

 https://github.com/ueberauth/guardian/blob/72df24d7e27e0a13ee7538c9d9537ae19ab60aff/lib/guardian.ex#L619

**Comment by yordis** [comment]
@jsangilve if you need to do some `custom` verification as the documentation describe then you add the callback. That is the propose of that callback.

**Comment by jsangilve** [comment]
@yordis yes, I understand that. I'm implementing the callback because I need to do some custom verification. The problem is that this `custom verify_claims` is called twice while running the app. 

So, my question is: **the reason why a custom `verify_claims` callback gets called twice seems to be because `Guardian` do it by itself (as I explained in the first post). Is this a bug or intended behavior?**

**Comment by yordis** [comment]
Feel free to open it again.

`verify_claims` is called twice.
  - On the `Token module`
  - On `your Guardian module`
