### ISSUE TITLE
Guardian 1.0: verify JWT toeken from Auth0

### ISSUE THREAD

**Issue by andreapavoni** [ueberauth/guardian#497]
Hello there,

I don't know if this is the right place to ask for help, I've also followed the old issue #211 but it looks outdated.

I'm trying to verify a JWT issued by Auth0 with Guardian 1.0 but I get several errors (from `invalid token` up to `missing JWT key`. I'm not new to elixir/phoenix in general, but I don't know too much how JWT should work.

I've tried both using RS256 and HS256 algos.

Here's my code:

```elixir
# config.exs
config :api, MyApp.Api.Auth.Guardian,
  allowed_algos: ["HS256"],
  verify_module: Guardian.JWT,
  issuer: System.get_env("API_AUTH0_DOMAIN"),
  verify_issuer: true,
  secret_key: System.get_env("API_AUTH0_SECRET")


# pipeline.ex
defmodule MyApp.ApiWeb.Auth.Guardian.Pipeline do
  alias MyApp.ApiWeb.Auth

  use Guardian.Plug.Pipeline,
    otp_app: :api,
    module: Auth.Guardian,
    error_handler: Auth.Guardian.ErrorHandler

  plug(Guardian.Plug.VerifyHeader, realm: "Bearer", claims: %{typ: "access"})
  plug(Guardian.Plug.LoadResource, allow_blank: true)
end
```

With the above code I always get something like this (formatted): `invalid_token: No secret key configured for JWT`

Does anyone have some hints about this? Thanks in advance.

**Comment by yordis** [comment]
Are you sure that `secret_key: System.get_env("API_AUTH0_SECRET")` is actually doing what you expect to do?

The error message is really descriptive and I just want to make sure that it is your setup issues.

**Comment by andreapavoni** [comment]
thank you @yordis, it was a matter of wrong certificate. solved with different package.

**Comment by randolphpark** [comment]
I am having a similar problem. 
Would be great if @andreapavoni can clarify what is the "different package"? Thanks

**Comment by andreapavoni** [comment]
@randolphpark I've removed `guardian` and installed `joken` package (to handle JWTs), then I wrote the rest of the glue code (plugs & co).
