### ISSUE TITLE
Accept runtime environment tuple for secret_key

### ISSUE THREAD

**Issue by williamweckl** [ueberauth/guardian#498]
Hi guys, I'm using distillery and trying to use the convention tuple to set environment variable secret_key and noticed I can't do it.

Error I'm getting:

```
FunctionClauseError: no function clause matching in :jose_jwk.from/1
```

Stack trace:

```
1
File "src/jose_jwk.erl" line 134 in :jose_jwk.from/1 (jose) [args]
2
File "src/jose_jwt.erl" line 182 in :jose_jwt.sign/3 (jose)
3
File "lib/guardian/token/jwt.ex" line 168 in Guardian.Token.Jwt.create_token/3 (guardian)
4
File "lib/guardian.ex" line 754 in Guardian.returning_tuple/1 (guardian)
5
File "lib/guardian.ex" line 581 in Guardian.encode_and_sign/4 (guardian)
```

My config at prod.exs:

```
config :accounts, Accounts.Guardian,
  secret_key: {:system, "GUARDIAN_SECRET"}
```

If I use `System.get_env("GUARDIAN_SECRET")` it works.
Using guardian `1.0.1` with elixir `1.6.4`

**Comment by williamweckl** [comment]
When I do it at config it will compile as a string, so if I build my application in a different environment that I run it the configuration value will be different...

Better explained at: https://hexdocs.pm/distillery/runtime-configuration.html

**Comment by yordis** [comment]
I didn't finish to read by so far

> NOTE: It is no longer recommended to use the {:system, "VAR"} convention, as it has inconsitent use in the community, and instead we’d rather push people towards an approach which works every time, rather than only sometimes.

So why are you trying to use that way?

**Comment by yordis** [comment]
From Distillery official documentation this method is not recommended.

**Comment by williamweckl** [comment]
@yordis 

Answering your question I'm using it because almost all my other libraries accepts this format, even phoenix uses it... If I can't use it at least I need a way to set it at runtime...

**Comment by yordis** [comment]
@williamweckl could be this what you are looking for

```
secret_key: {MyModule, :function_name, [:some, :args]}
```

**Comment by williamweckl** [comment]
@yordis yes! this will work for me! thank you!

**Comment by pablocrivella** [comment]
Having this same issue, even tho the CHANGELOG says this is supported https://github.com/ueberauth/guardian/blob/master/CHANGELOG.md#v-0140
