### ISSUE TITLE
Confusion with branches and tags

### ISSUE THREAD

**Issue by marpo60** [ueberauth/guardian#500]
Thanks for this package.

I was going to create PR to remove a `remember_me` documentation from the README in 1.0.x (https://github.com/ueberauth/guardian/blame/v1.0.1/README.md#L125).

It got reverted and added to v1.1.x release
https://github.com/ueberauth/guardian/pull/424
https://github.com/ueberauth/guardian/pull/419

When I looked for the branch v1.0.x it was not in place and then by looking at the branches and tags  I got confused.

There is a v1 branch and also a v1_final branch, but all of them are prior v1.0.1 tag v1.0.0 tag and v1.0.0-beta.1 tag.

I think v1_final and v1 are useless and only generates confusion. It would be better to have a v1.0.x branch at the latest release of v1.0.x (currently v1.0.1) and remove v1 and v1_final

Thoughts?

**Comment by doomspork** [comment]
Agreed. We'll nuke the extra branches. There's no reason for us to keep an older version around and worry about backporting. That's not something that's been done for many, if any, Elixir packages. I think things are moving fast enough to expect folks to upgrade.
