### ISSUE TITLE
Authentication pipeline for multiple logins schemes

### ISSUE THREAD

**Issue by grounded-warrior** [ueberauth/guardian#501]
I can't seem to figure out how to have two different lookups for admin and members, there are seperate tables so i would like to be able do something like

     def resource_from_claims(claims) do
        id = claims["sub"]
        user = Users.get_user!(id)
        {:ok, user}
     end

     def admin_resource_from_claims(claims) do
        id = claims["sub"]
        user = AdminUsers.get_user!(id)
       {:ok, user}
     end

They have very different data model which I why i dont just want an `is_admin` flag as I have seen suggested.  I had this working pre-1.0 using a serializer and 

     def for_token(user = %User{}), do: { :ok, "User:#{user.id}" }
     def for_token(user = %AdminUser{}), do: { :ok, "Admin User:#{user.id}" }

but I can't seem to figure out how to do the same thing as there does not seem to be the same pattern matching ability with `resource_for_claims`

**Comment by yordis** [comment]
@grounded-warrior you could use the same pattern with the `claims["sub"]` indeed.

```
  def resource_from_claims(%{"sub" => "User:" <> id} = _claims) do
  end
  def resource_from_claims(%{"sub" => "Admin:" <> id} = _claims) do
  end
```
