### ISSUE TITLE
Guardian.Plug.sign_out() doesn't seems to revoke the token

### ISSUE THREAD

**Issue by loustak** [ueberauth/guardian#502]
In my application sign_out doesn't seems to revoke token get by Guardian.Plug.sign_in

Here is how I get a token :
`Test.Guardian.Plug.sign_in(conn, user, %{claim: "access"}, ttl: {30, :days})`

And here is how I revoke it:
`Test.Guardian.Plug.sign_out(conn)`

I can get the token (with `Test.Guardian.Plug.current_token(conn)` ) before the call to sign_out **but also** after the call to sign_out wich shouldn't happend no?

**Comment by yordis** [comment]
What is the value of `Test.Guardian.Plug.current_token(conn)` after sign_out ?

**Comment by loustak** [comment]
It's the token itself

**Comment by dave-bell** [comment]
I am seeing similar behaviour.  In my case I have the following call to sign in: `App.Guardian.Plug.sign_in(user, key: :admin)` and on sign out: `App.Guardian.Plug.sign_out(key: :admin)`.  I spent some time looking into the data in the session and I noticed that upon sign in I have a `guardian_default_token` in my session (`conn.private.plug_session`).  Working through the sign out path the code is removing `guardian_admin_token` from the session.

It appears that `sign_in` isn't loading up the session with the same key that sign out expects.

**Comment by dave-bell** [comment]
When I correctly call `App.Guardian.Plug.sign_in` then keys in the session are as expected.  In my above example `sign_in` should have been called as follows: `App.Guardian.Plug.sign_in(conn, user, %{}, key: :admin)`

**Comment by yordis** [comment]
@loustak which `conn` are you passing down?

Could you please post the full test code so I can see what you are doing it.

**Comment by loustak** [comment]
`@loustak which conn are you passing down?`
I'm not really sure about what you mean there. 

[Link to my project.](https://github.com/loustak/Flux/blob/master/back/web/controllers/token_controller.ex)

I have also another question. I read somewhere that the jwt is stored in "connections". But I don't understand what are connections when speaking about Phoenix. Is this something in memory? My concern here is the scalabitility of this storage.

Thanks for help !

**Comment by yordis** [comment]
Where is the link to the test where you are trying to make it pass.

> @loustak which conn are you passing down?
I'm not really sure about what you mean there.

I am trying to see how you are using the package and make sure that you are using the write connection.

Please do not merge one thing with the other one, keep it clean and better ask those questions on Slack channel where people could help you with it.

> I have also another question. I read somewhere that the jwt is stored in "connections". But I don't understand what are connections when speaking about Phoenix. Is this something in memory? My concern here is the scalabitility of this storage.

JWT are stored on your cookie and/or your clients storage and send it every request on the header. JWT are stateless which means you don't store them on the server but your clients.

**Comment by yordis** [comment]
Feel free to open the issue if the problem persists.
