### ISSUE TITLE
current resource expiration

### ISSUE THREAD

**Issue by MeterSoft** [ueberauth/guardian#504]
i logged in  my user as 
`Guardian.Plug.sign_in(resource, %{}, ttl: {1, :minute})`
And after some time do
`Guardian.Plug.current_resource(conn)`
and i expect that it should return error because token is expired but it return my user. How i should check that my current session is expired?

**Comment by yordis** [comment]
What does `Guardian.Plug.current_resource(conn)` give you back after you made sure that the token expired?

**Comment by MeterSoft** [comment]
```
%Olist.Users.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">,
 favorites: #Ecto.Association.NotLoaded<association :favorites is not loaded>,
 global_id: "111", id: 1,
 inserted_at: ~N[2018-06-08 12:28:45.935702],
 postings: #Ecto.Association.NotLoaded<association :postings is not loaded>,
 refresh_token: nil,
 remote_favorites: #Ecto.Association.NotLoaded<association :remote_favorites is not loaded>,
 updated_at: ~N[2018-06-08 12:28:45.939106], username: "name"}
```

**Comment by yordis** [comment]
Could you share your pipeline configuration so I can see which functions you are using for load the resource.

Did you use `  plug Guardian.Plug.EnsureAuthenticated`?

**Comment by hassox** [comment]
Is this part of a really long web request or part of a socket configuration?

**Comment by MeterSoft** [comment]
@yordis 
```
defmodule Olist.Guardian.AuthPipeline.BrowserAuth do
  import Olist.Auth, only: [load_current_resource: 2]

  use Guardian.Plug.Pipeline, otp_app: :olist,
                              module: Olist.Guardian,
                              error_handler: Olist.AuthErrorHandler

  plug Guardian.Plug.VerifySession
  plug Guardian.Plug.EnsureAuthenticated
  plug Guardian.Plug.LoadResource
  plug(:load_current_resource)
end

pipeline :browser_session do
    plug Olist.Guardian.AuthPipeline.Browser
  end


```

**Comment by MeterSoft** [comment]
looks like that expires token not works on local host. On production mode it works. I dont know why but now now i have another issue. 
```
defmodule Olist.Guardian.AuthPipeline.Browser do
  use Guardian.Plug.Pipeline, otp_app: :olist,
                              module: Olist.Guardian,
                              error_handler: Olist.AuthErrorHandler

  plug Guardian.Plug.VerifySession
  plug Guardian.Plug.LoadResource, allow_blank: true
end
```
when i trying visit root path with this pipeline i got error
```
invalid_token, token_expired
```
why it trigger this error if i do not have EnsureAuthenticated for root path?
Also haw i can check if token expired and it should redirect me to root path

**Comment by MeterSoft** [comment]
@hassox i di nit use docker. session generate with
```
Olist.Guardian.Plug.sign_in(resource, %{}, ttl: {15, :minute})
```
Please forget about expiration. It works on production and it is enought for me.
i found that ` plug Guardian.Plug.VerifySession` use for check that token is expired so i just removed it for my root pipiline and now i get invalid token error only for auth paths. So now i have one problem. How i can redirect user to login path if his session is expired?

**Comment by yordis** [comment]
@MeterSoft is this still an issue?

**Comment by yordis** [comment]
Feel free to open the issue if the problem persists.
