### ISSUE TITLE
Guardian.decode_and_verify is throwing %UndefinedFunctionError 

### ISSUE THREAD

**Issue by joshchernoff** [ueberauth/guardian#514]
I kept getting an Invalid Token response so I decided to talk over the code. 

While in the Guardian.Plug.VerifyHeader Plug 
https://github.com/ueberauth/guardian/blob/master/lib/guardian/plug/verify_header.ex#L87

I noticed that Guardian.decode_and_verify would return 
```
{:error,
 %UndefinedFunctionError{
   arity: 2,
   exports: nil,
   function: :config,
   module: PolymorphicProductionsWeb.Auth.Guardian,
   reason: nil
 }}
```

Any ideas what wrong? 

Heres my PolymorphicProductionsWeb.Auth.Guardian
```
defmodule PolymorphicProductions.Auth.Guardian do
  use Guardian, otp_app: :polymorphic_productions

  def subject_for_token(resource, _claims) do
    sub = to_string(resource.id)
    {:ok, sub}
  end

  def subject_for_token(_, _) do
    {:error, :reason_for_error}
  end

  def resource_from_claims(claims) do
    case PolymorphicProductions.Accounts.get_user(claims["sub"]) do
      nil -> {:error, "User not found"}
      user -> {:ok, user}
    end
  end

  def resource_from_claims(_claims) do
    {:error, :reason_for_error}
  end

end

```

**Comment by joshchernoff** [comment]
Let it be known that if you have a typo in your module name for your given Pipeline config. ie

```
use Guardian.Plug.Pipeline,
    otp_app: :polymorphic_productions,
    module: MY_TYPO_HERE.Auth.Guardian,
```
You will find your self going down this same rabbit hole.

**Comment by mtomov** [comment]
Hey @joshchernoff  - just wanted to thank you for posting the issue and replying to it as well ... spent a good day chasing this one - in my case, it was just 2 letters swapped .. At least I got to know the internals of the library a bit better : )  Thanks again!
