### ISSUE TITLE
Push newest release to hex.pm

### ISSUE THREAD

**Issue by harmon25** [ueberauth/guardian#516]
The "new" `1.1.0` release on the releases page which fixes the UUID problem has not been pushed to hex!

Need to change version to `1.1.1` or something other than `1.1.0` as that was the previous hex release version.

**Comment by yordis** [comment]
We need to push, `1.1.1`. Because we didnt create a release I had to do it for fix this https://github.com/ueberauth/guardian/issues/513

@hassox @doomspork @scrogson could somebody create a release for Hex and also here on Github?

**Comment by zacksiri** [comment]
Yep, someone, please update this hex.

**Comment by williamweckl** [comment]
+1

**Comment by hassox** [comment]
Thanks for the ping. 1.1.1 is published
