### ISSUE TITLE
:invalid_token on page that does not require authentication

### ISSUE THREAD

**Issue by mitkins** [ueberauth/guardian#517]
On my home page, I'd like to show information depending on if the user authenticated. Here's what my pipeline looks like:

``` Elixir
defmodule Zoinks.Guardian.LoadResource do
  @claims %{typ: "access"}

  use Guardian.Plug.Pipeline,
    otp_app: :zoinks,
    module: Zoinks.Guardian,
    error_handler: Zoinks.Guardian.LoadErrorHandler

  plug Guardian.Plug.VerifySession, claims: @claims
  plug Guardian.Plug.VerifyCookie
  plug Guardian.Plug.LoadResource, allow_blank: true
end
```

This is working as intended. However, when the access token expires and the user accesses the home page, then the error handler is invoked with an `:invalid_token`. Here's what the error handler looks like:

``` Elixir
defmodule Zoinks.Guardian.LoadErrorHandler do
  import Plug.Conn
  use ZoinksWeb, :controller

  def auth_error(conn, {type, _reason}, _opts) do
    conn
  end
end
```

In the case of an `:invalid_token` (on the home page) I'd like execution to continue (rather than be [halted](https://github.com/ueberauth/guardian/blob/64f16a643c9742cea1ea0f19cad8225c0f293022/lib/guardian/plug/verify_session.ex#L65) by `VerifySession`). Is there a way to achieve what I want?

**Comment by mitkins** [comment]
I think this applies to the latter part of #504. Looking at `VerifyCookie` @Hanspagh opted to include the following code:

``` Elixir
def call(conn, opts) do
  with ...
  else
    :no_token_found ->
      conn

    # Let the ensure_authenticated plug handle the token expired later in the pipeline
    {:error, :token_expired} ->
      conn

    {:error, reason} ->
      conn
      |> Pipeline.fetch_error_handler!(opts)
      |> apply(:auth_error, [conn, {:invalid_token, reason}, opts])
      |> halt()

    _ ->
      conn
  end
end
```

In the case of `:token_expired`, calling the error handler is optional - depending on whether `EnsureAuthenticade` is in the pipeline.

I've made a copy of the `VerifySession` plug and added the `{:error, :token_expired}` match. So far it seems to be doing what I expect.

**Comment by Hanspagh** [comment]
I guess its a matter of how you understand the verify part of `VerifySession`, some might argue that an expired token is not valid and there for should not get past the Plug, but since its handled otherwise the `VerifyCookie` plug, it would make sense to align the two.

**Comment by mitkins** [comment]
I can definitely see that point of view (in terms of not allowing `VerifySession` when the token is not valid and the fact that this would introduce a breaking change). Though I quite like the idea that the `EnsureAuthenticated` plug is where the error is actually raised, to me it's an intuitive way of saying "this page must be protected".

I'm assuming that the alternative _is_ to create my own plug with the desired behaviour. If this is the case, then maybe it's just a matter of mentioning the scenario in the documentation somewhere (e.g. https://github.com/ueberauth/guardian/blob/master/guides/plug/pipelines.md). It's a little bit of a gotcha for an inexperienced elixir/web developer like me.

Now that I think about it, how does the refresh token mechanism work? If a session token expires, doesn't it just throw the `:invalid_token` error (and break the pipeline before `VerifyCookie` is called)?

**Comment by yordis** [comment]
@mitkins I don't believe that there is an issue, to be honest.

Everything depends on the order and the plugs that you use in your business and all of them depends on the app.

But please if you think otherwise I would love to see a descriptive message with your doubt and suggestions on what we need to do.

**Comment by mitkins** [comment]
I suspect that there isn't either. I realised what I'm after is a best practice. That is, in the case where:

* A page does not require authentication; and
* I would like to conditionally show user info (if it's available); and
* The token has expired; and
* I don't want to disrupt the page from loading

What's the best practice? Any advice is appreciated, but if you would like me to close the issue, then I'm happy to.
