### ISSUE TITLE
JWT invalid after production app image rebuild

### ISSUE THREAD

**Issue by MarkPare** [ueberauth/guardian#521]
1. I'm an authenticated user that has been issued a jwt.  Everything works fine.
2. The production application's docker image is rebuilt, redeployed, and the phoenix server is restarted.
3. My jwt token issued before the rebuild is no longer valid.

I'm having trouble finding what would be causing this.  Looks like the secret key used in `config.exs`guardian config will always be the same across builds.

Any help is appreciated!

Also, thanks for the incredible library!

**Comment by yordis** [comment]
How are you setting up the secret key?
