### ISSUE TITLE
secret_not_found when attempting to build key

### ISSUE THREAD

**Issue by AlexRiedler** [ueberauth/guardian#523]
Guardian v1.1.1 (haven't tried previous versions yet)

I keep getting `{:error, :secret_not_found}` when attempting to encode and sign a token.

My example project is here: https://github.com/AlexRiedler/my_project/tree/guardian-setup and you can clearly see the key is set here: https://github.com/AlexRiedler/my_project/blob/guardian-setup/config/config.exs#L28

## Details
`no match of right hand side value: {:error, :secret_not_found}`
From:
`{:ok, token, claims} = MyProject.Guardian.encode_and_sign(user)`

## On v1.0.1

No secret key configured for JWT

**Comment by hassox** [comment]
Hey there. An can you please point me at the implementation for `MyProject.Guardian`

**Comment by AlexRiedler** [comment]
OMG I just realized I did the same error as https://github.com/ueberauth/guardian/issues/429 typed opt instead of otp ... ; weird that the error changed though? should I keep this open?

**Comment by sheltont** [comment]
> OMG I just realized I did the same error as #429 typed opt instead of otp ... ; weird that the error changed though? should I keep this open?

same mistake. I typed "opt_app".

**Comment by HiiMartins** [comment]
> OMG I just realized I did the same error as #429 typed opt instead of otp ... ; weird that the error changed though? should I keep this open?

I don't believe. I made the same mistake
