### ISSUE TITLE
Cutomizing token headers

### ISSUE THREAD

**Issue by dubert** [ueberauth/guardian#536]
I'm trying to replicate this exact format of token:
(This is issued by Twitch, and I'm building an extension service that interacts with their API)
```
{
  "exp": 1573786888,
  "opaque_user_id": "ARIGM9CV7RpigqPXUUS",
  "role": "viewer",
  "pubsub_perms": {
    "listen": [
      "broadcast",
      "global"
    ]
  },
  "channel_id": "265737932",
  "iat": 1542250888
}
```
I can add claims to cover `channel_id`, `pubsub_perms`, `role`, and `opaque_user_id`, but I can't remove: `"aud"`,`"iss"`,`"jti"`,`"nbf"`,`"sub"`,`"typ"`.

Examining the [JWT documentation](https://tools.ietf.org/html/rfc7519#section-4.1) only `exp` is required while the rest are optional.

Digging into the source code here: https://github.com/ueberauth/guardian/blob/master/lib/guardian/token/jwt.ex#L271-L283
I can see that these values are being hard coded, there is no way to modify or remove them.

Are there any plans to allow this customization?

Or is the recommended solution to use a different token generation library? I'd prefer not to since I'm already using Guardian and it's doing everything else great.

**Comment by yordis** [comment]
@dubert to be honest, I would recommend you to use `jose` or something more low level for your JWTs.

Guardian wasn't meant to be used as JWT related package but for authentication based on some sort of token.

**Comment by hassox** [comment]
@dubert if you want to omit some keys from your token you can. Use the `build_claims` callback on your guardian impl module.

```elixir
defmodule MyApp.Guardian do
  use Guardian, otp_app: :my_app

 # snip ...

def build_claims(claims_so_far, resource, options) do
  claims =
    claims_so_far
    |> Map.drop(["aud", "iss", "jti", "nbf", "sub", "typ"])
  
  {:ok, claims}
end

# snip ...
end
```

**Comment by dubert** [comment]
Thanks! I believe this solves my issue.
