### ISSUE TITLE
Receiving a `secret_not_found` message on login action

### ISSUE THREAD

**Issue by mc962** [ueberauth/guardian#559]
I've been trying `guardian` on an app together with `absinthe` to make a GraphQL API Phoenix application.

I got most of it working, and even the sign_up action works as expected. However, for the `login` action I am receiving a `secret_not_found` message in the response (no errors in the console).

From what I can tell, I am probably having an issue with `guardian`, as the message seems to be from either:
[jwt.ex](https://github.com/ueberauth/guardian/blob/3c91f9f367d764537ed3f4039df71d321ca06fe4/lib/guardian/token/jwt.ex#L165)
and/or
[token.ex](https://github.com/ueberauth/guardian/blob/c4307390cb3c9e44ba4e6953dbe6d8d349966f0c/lib/guardian/token.ex#L23)

but I'm not really sure what issue I'm having, as from what I can tell, it's all set up more or less correctly. I did see [this git issue](https://github.com/ueberauth/guardian/issues/523) with a similar error message, but I think I'm not having the same problems, as my Guardian module looks set up correctly from what I can see.

Here is the app: https://github.com/mc962/guack

**Comment by yordis** [comment]
@mc962 your config looks fine except that I don't know if this is happening on production. This definitely seems to be something on your side.

**Comment by yordis** [comment]
Check the name of your OTP, the name of your module and so on

**Comment by mc962** [comment]
🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 
Found it, it was the name of the module after all.

I had been using a context called `Authentication`, where the `Guardian` module was namespaced behind that module.

But my dev.exs config was asking for `MyAppName.Guardian`, instead of what I had,  which was `MyAppName.Authentication.Guardian`. That's what I get for trying to be organized 😆 

Thanks for the advice.
