### ISSUE TITLE
Elixir 1.8 deprecations

### ISSUE THREAD

**Issue by garretttaco** [ueberauth/guardian#569]
The release of [Elixir v1.8.0](https://github.com/elixir-lang/elixir/releases/tag/v1.8.0) comes with a few hard deprecations. I noticed that one in particular is being used in this library. 
> [System] :seconds, :milliseconds, etc. as time units is deprecated in favor of :second, :millisecond, etc.

**Comment by doomspork** [comment]
@garretttaco thanks for bringing this to our attention. A PR to fix these would be greatly appreciated 😁

**Comment by garretttaco** [comment]
@doomspork I will get to it as soon as I can! Things are swamped at work but I figured I would at least bring it to others' attention.

**Comment by sjoconnor** [comment]
I just ran into this as well, but it looks like this has already been fixed here https://github.com/ueberauth/guardian/pull/557 and is available in v1.2.1.

**Comment by garretttaco** [comment]
@sjoconnor Awesome, I did not see that. I upgraded and it appears to have fixed the issue. Thanks for pointing that minor version update. Since this is solved, I am closing this issue.
