### ISSUE TITLE
Some minor issues with Getting started tutorial

### ISSUE THREAD

**Issue by corroded** [ueberauth/guardian#591]
Hi,

I am currently trying to follow the original article by Tyler and ended up here. I've noticed some minor snags while following it so dropped by to list them down and maybe do a PR for the corrections if deemed necessary?

So far I am on Tyler's step 4 which is password hashing. Here are a couple of things I noticed while comparing the old article and the current README [here](https://github.com/ueberauth/guardian/blob/master/guides/tutorial/start-tutorial.md):

1) [comeonin v5 is not needed in mix.exs anymore](https://github.com/riverrun/comeonin/blob/master/UPGRADE_v5.md)
2) [comeonin actually recommends Argon2 as the hashing library to use](https://github.com/riverrun/comeonin/wiki/Choosing-the-password-hashing-library)
3) I don't see any mention of tests, but I would have expected the autogenerated ones to be passing - but they don't. It's basically because we need to compare the hashed passwords instead of the plain text ones.

Again, they are all pretty minor so far, but is this something that can be corrected? If so I can create a PR for these changes :) (Also will continue to follow the other steps tonight and see if I need to add more notes here)

Cheers!

**Comment by yordis** [comment]
@corroded PR welcome for sure!

**Comment by Hanspagh** [comment]
Closed by #593
