### ISSUE TITLE
v1.2.1 has a typo in mix.exs (`runtume`), can we get a 1.2.2 release?

### ISSUE THREAD

**Issue by JamesFerguson** [ueberauth/guardian#594]
The typo was fixed in #568 back in January but there's no release available that has the fix. This is breaking an editor plugin I use (c.f. https://github.com/KronicDeth/intellij-elixir/issues/1495).

Could we get a point release?

**Comment by yordis** [comment]
Moved to #588

**Comment by kreba** [comment]
Yes, please give the release button some love.

**Comment by yordis** [comment]
Done

**Comment by kreba** [comment]
Whoa, a whole major release! :astonished:  
Thanks a bunch! :smile: :+1:

**Comment by yordis** [comment]
@kreba the breaking change is introduced by `Phoenix 1.3` and we decided to split the packages so we are not required to introduce breaking changes in Guardian itself again because of a dependency.
