### ISSUE TITLE
Guardian.Plug.authenticated?/2 should have an authenticated?/1 equivalent

### ISSUE THREAD

**Issue by SampsonCrowley** [ueberauth/guardian#633]
It's not documented what needs to be provided for `opts` in the hexdocs, the `opts` arg should be implemented as an optional argument

**Comment by SampsonCrowley** [comment]
Ok, after finding the same issue on stackoverflow, there should be documentation that the "Plug" needs to be under the application Guardian module, not the global one

**Comment by doomspork** [comment]
@SampsonCrowley we would love PRs to improve documentation :+1:

**Comment by SampsonCrowley** [comment]
If you want me to contribute, don't close my issues before they're actually fixed

**Comment by SampsonCrowley** [comment]
The point of issues is so that contributors _know what needs to be done_

**Comment by doomspork** [comment]
Thanks for the feedback @SampsonCrowley 👍

**Comment by SampsonCrowley** [comment]
Why even allow issues, if your only response is going to be "fix it yourself if you don't like it" and closing?
