### ISSUE TITLE
Guardian.Phoenix.Socket is not available

### ISSUE THREAD

**Issue by SampsonCrowley** [ueberauth/guardian#634]
The ONLY place that it's mentioned is in the `CHANGELOG.md`

Seeing as MOST elixir developers are looking at the current Hex Docs, not scouring the github, it took me an absurdly long amount of time to figure out that Guardian.Phoenix.Socket was moved to a completely separate package.

The Hex Docs severely need to be updated to the latest version

Not even Issue #216 mentions that it was ACTUALLY DONE, the wording of the thread makes it look like that this separation was not going to happen

**Comment by aaron-price** [comment]
This just saved me a lot of time. I've been trying to get it working with phoenix live views, but of course it wants a Conn, not a Socket.

Didn't even know there was a separate package for guardian phoenix. See:
https://hex.pm/packages/guardian_phoenix
https://github.com/ueberauth/guardian_phoenix

**Comment by doomspork** [comment]
@SampsonCrowley / @aaron-price pull requests to improve the documentation are always welcome.

**Comment by SampsonCrowley** [comment]
And if I find time to do so, I absolutely will. But as I'm not a maintainer of this project, there are other projects that will get that time first. Regardless of who finds the time to do the work, the issue still stands that this is a glaring gap in documentation, that should have been updated _with_ the change being made

**Comment by doomspork** [comment]
Thanks for the report @SampsonCrowley

**Comment by aaron-price** [comment]
Eh, it's all free, you can't have high expectations. You guys still do great work! 

If I ever figure it out, I'll make a PR, but more likely I'll just give up and do my own auth from scratch.

**Comment by doomspork** [comment]
Thanks @aaron-price! It’s unfortunate when people see open source (and maintainers) as something they’re entitled too without compensation or contributions. Thankfully they’re few and far between!

Those of us who’ve contributed and work to maintain these packages _want_ them to be perfect but alas we have our own obligations (both in work and personal lives) **and** we all have different backgrounds and levels of experience so what some may see as “glaring” deficiencies are rather obvious to others.  

Constructive feedback and contributions are always welcome 😁
