### ISSUE TITLE
2.1 is not published yet

### ISSUE THREAD

**Issue by MarkNijhof** [ueberauth/guardian#647]
I am just curious if there is a reason 2.1 has not been published yet as I did see it in the Changelog :) I am using the 2.1.0 branch now so I get the sliding cookie functionality.

**Comment by Hanspagh** [comment]
@doomspork. Can you add me to hex, then I will publish this version

**Comment by Hanspagh** [comment]
@doomspork. Can you add me to hex, then I will publish this version

**Comment by doomspork** [comment]
Sorry about that @MarkNijhof! @Hanspagh I added you to guardian just now. I'll work on the rest of the packages this evening.

**Comment by Hanspagh** [comment]
This is now resolved
