### ISSUE TITLE
[Proposal] Add callback to revoke all tokens of a resource

### ISSUE THREAD

**Issue by thiamsantos** [ueberauth/guardian#651]
In my use case, we are using guardian_db to persist the tokens. And when a user changes its password, we need to revoke all tokens for that user. Today we don't have a way to do that on guardian without relying on implementation details of guardian_db.

I'm added this to my guardian module. It deletes all tokens of given resource.

```elixir
  def revoke_all(resource) do
    with {:ok, sub} <- subject_for_token(resource, %{}) do
      {amount_deleted, _} = Guardian.DB.Token.query_schema()
      |> where([token], token.sub == ^sub)
      |> Repo.delete_all()

      {:ok, amount_deleted}
    end
  end
```

I would love to have this feature on guardian itself. WDYT? This feature is worth adding to the guardian and guardian_db? I'm open to send a PR if that's the case.

**Comment by Hanspagh** [comment]
Do we actually need to need any updates in Guardian to do this?
I am thinking to have `revoke_al`l makes no sense without havning `guardian_db`, so I would prefer that it was only implemented in `guardian_db`. Maybe I am missing something?

**Comment by thiamsantos** [comment]
@Hanspagh I'm really not sure. 

Most of the behaviors of `guardian_db` are defined as callbacks of guardian itself. One example is the `revoke` function, even though it is defined in guardian, it does nothing without using guardian_db or something similar.

Because of that, I think it may make sense for `revoke_all` to be implemented in the same way. We add it to the guardian module and add the `guardian_db` callbacks for it. 

WDYT?

**Comment by doomspork** [comment]
@thiamsantos I understand @Hanspagh's hesitation, since this functionality is rather specific to GuardianDB it would feel out of place in Guardian. At the same time, I can understand the need for this functionality but there may be a way to achieve it without adding a callback.

What if we replied on an option for this? Right now we use `"aud"` and `"jti"` to look up what token to revoke. If we make those columns configurable changing it to `"sub"` should work as a revoke all.

Something like this (not requested, just captures my thinking):ng:

```elixir
defmodule Guardian.DB do
  def on_revoke(claims, jwt, opts) do
   query_columns = Keyword.get(opts, :query_columns, ["aud", "jti"])
    
    claims
    |> find_tokens(query_columns)
    |> Enum.each(&Token.destroy_token(&1, claims, jwt))

    {:ok, claims}
  end

  defp find_tokens(claims, opts) do
    query = Enum.reduce(query_columns, query_schema(), fn col, query ->
      where(query, [t], field(t, col) == ^Map.get(claims, col)))
    end

    Guardian.DB.repo.all(%{prefix: prefix() | query})
  end
end
```

When implementing the `on_revoke` callback in our app's Guardian module we just pass in the desired lookup column:

```elixir

defmodule ExampleApp.Guardian do
  def on_revoke(claims, token, opts) do
    with {:ok, _} <- Guardian.DB.on_revoke(claims, token, query_columns: ["sub"]) do
      {:ok, claims}
    end
  end
end
```

**Comment by thiamsantos** [comment]
@doomspork I think that would work. 

But for me that would be a strange interface for the API, passing the `sub` as option. As usually by passing the token we would think that would only delete the token itself and not all the tokens for that resource, the API would be a little dubious in my opinion.

I was thinking a little about it in the last days and I think what @Hanspagh said makes sense. We could introduce this feature without having to change guardian itself.

We could just add a new function to `Guardian.DB` and just document in the readme of guardian_db how to use it. I think would be something like that:

```elixir
def revoke_all(resource, claims) do
  with {:ok, sub} <- subject_for_token(resource, claims) do
    Guardian.DB.revoke_all(resource)
  end
end
```

WDYT?
