### ISSUE TITLE
:crypto.hmac/3 undefined due to being deprecated --> Need to bump Jose to 1.11

### ISSUE THREAD

**Issue by fantypants** [ueberauth/guardian#685]
Hello, 
Jose deps need to be bumped to 1.11 to fix the following:

`Request: POST /login
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function :crypto.hmac/3 is undefined or private
        (crypto 5.0.2) :crypto.hmac(:sha512, "Salt", "Key")
`

I can open a PR if needed.

Current: :jose, 1.8
Solution: :jose, 1.11

**Comment by yordis** [comment]
@ueberauth/developers any objection to changing the minimal requirements to be a bit higher?

**Comment by yordis** [comment]
Hey there, as https://github.com/ueberauth/.github/blob/master/SECURITY.md#elixir-and-erlangotp `elixir v1.11` is the minimal that Elixir itself supports.

I am gonna close this one, you will need to upgrade to a higher version.
