### ISSUE TITLE
Is guardian relying on JWT's fixed side ?

### ISSUE THREAD

**Issue by phtrivier** [ueberauth/guardian#689]
I'm using ueberauth and guardian to authenticate with Auth0.
Recently they annonced that they might change the size of the generated tokens and access code. 

https://support.auth0.com/notifications/61df51092bf8f3000b5bfd48

Could this have any impact when using ueberauth ? Are there specific things to check ?

**Comment by yordis** [comment]
![Screen Shot 2022-03-26 at 11 39 06 AM](https://user-images.githubusercontent.com/4237280/160246745-5b86ff3a-5a0c-407e-914f-d8ae1f023a88.png)

@phtrivier I can't read the shared link.

**Comment by phtrivier** [comment]
Sorry about that. The issue was a change of the Access Tokens and/or Authorization Codes issues by Auth0 ; they used to isse fixed-size opaque Access Token, and are migrating to variable size.

I was able to do some tests and get help from the support team, so we can close this.
