### ISSUE TITLE
Opaque errors when token verification fails

### ISSUE THREAD

**Issue by rawnsley** [ueberauth/guardian#711]
### Problem Statement

Caveat: I am new to both Guardian and Elixir

While trying to get the [`decode_and_verify`](https://github.com/ueberauth/guardian/blob/cdfdd3aba34ace65098d0b1b43369988fa1bdfe6/lib/guardian.ex#L629) function working, I was thwarted by obscure error messages. In the end my problem was fixed by being explicit about the allowed algorithms, but the error returned by this function was always `CaseClauseError{term: {:error, :badarg}}}`

I think this is because the root error is returned by [`decode_token`](https://github.com/ueberauth/guardian/blob/a6efdacd67cee6ca533a9b9cba398ca7f2e3abe0/lib/guardian/token/jwt.ex#L320), then [`returning_tuple`](https://github.com/ueberauth/guardian/blob/cdfdd3aba34ace65098d0b1b43369988fa1bdfe6/lib/guardian.ex#L771) maps it to `{ :error, _ }` (already striping out any useful info), and then the calling function has no matching case clause anyway so it throws a generic `CaseClauseError`.

This exception is caught in `decode_and_verify` and an error message is returned, but there is no chance of debugging where the failure originally occured.

I'm not sure what the right behaviour should be in this case or what is canonical Elixir, but as it stands I ended up having to reproduce the call chain line-by-line in my client code until I found the problem, which isn't ideal.

**Comment by f-francine** [comment]
Hello, @rawnsley! 
Perhaps a log message would be helpful? At least it would make it easier to debug the problem

**Comment by yordis** [comment]
@f-francine thank you so much for the help.

--- 

@rawnsley do you mind filling up the "Solution Brainstorm" I am not sure what you are asking us to do or what you would propose.

Or even much better, since you already know how to replicate the issue and whatnot, create a PR with the proposed solution. I am here to help you with it as much as I can.
