### ISSUE TITLE
Breaking Change on 2.3.1 - Can't encode Bitwise Permissions

### ISSUE THREAD

**Issue by pedromvieira** [ueberauth/guardian#717]
### Steps to Reproduce

After upgrade from 2.3.0 to 2.3.1 old perms_map dont work.

Unable to find a clue in Changelog:

 v2.3.1
Change compile time loading of configuration to only load permissions allowing the app to change things like ttl or secret key at runtime

### Expected Result

```
defstruct perms_map: %{
              account_viewer: %{
                account: [
                  :read,
                  :dashboard
                ]
              },
}

alias MyApp.Guardian
test = %{
  account: [:read, :dashboard]
}
test |> Guardian.encode_permissions!()

%{account: 123}

```
PS: some bitwise number.

### Actual Result

** (Guardian.Permissions.PermissionNotFoundError) Elixir.MyApp.Guardian Type: account Missing Permissions: read, 
dashboard

**Comment by pedromvieira** [comment]
I think that on 2.3.1 and ongoing need to define on config.exs.

base_permissions_list = [
  :read,
  :export_drilldown,
  :export_reports,
  :export_campaigns,
  :export_messages,
  :export_people,
  :export_templates,
  :template,
  :people,
  :campaign,
  :write,
  :delete,
  :dashboard
]

config :my_app, MyApp.Guardian,
  allowed_algos: ["HS512"],
  issuer: "myapp",
  token_ttl: %{
    "reset" => {10, :minutes},
    "magic" => {10, :minutes},
    "access" => {30, :minutes},
    "user" => {2, :hours},
    "myuser" => {2, :hours},
    "company" => {52, :weeks}
  },
  allowed_drift: 2000,
  secret_key: Application.compile_env(:peoplex_services, :guardian_secret_key),
  permissions: %{
    account: base_permissions_list,
    group: base_permissions_list,
    mgmt: base_permissions_list
  }

**Comment by yordis** [comment]
Do you mind creating an example project showcasing the issue or much better to create a PR?

**Comment by yordis** [comment]
cc: @geofflane 😭

**Comment by phishx-docs** [comment]
It works with all permissions in config.exs. My suggestions, since this is a "new behaviour", is to enhance documentation.
We use Guardian for more than 5 years, and our list of permissions grew since.

**Comment by pedromvieira** [comment]
> Do you mind creating an example project showcasing the issue or much better to create a PR?

It works as intended with all permissions in config.exs. My suggestions, since this is a "new behaviour", is to enhance / clarify documentation. The changelog in our opinion it is not clear enough.
We use Guardian for more than 5 years, so our list of permissions grew since and we didn't bother updating back our config.exs.

**Comment by yordis** [comment]
@pedromvieira do you mind opening a PR about the topic?

**Comment by yordis** [comment]
@pedromvieira I will encourage you to improve the documentation based on your experience. I am going to close the issue for now.
