### ISSUE TITLE
Move to Elixir 1.14 and otp 25

### ISSUE THREAD

**Issue by apoorv-2204** [ueberauth/guardian#720]
### Problem Statement

I want to purpose to move the current code base to latest elixir and Erlang/otp version.

**Comment by adonig** [comment]
Or make it Elixir 1.15 and OTP 26 😅

**Comment by apoorv-2204** [comment]
why not

**Comment by yordis** [comment]
You could upgrade your app today. I upgraded the CI pipeline regardless.
