### ISSUE TITLE
Docs not working on hexdocs.pm

### ISSUE THREAD

**Issue by aussiegeek** [ueberauth/guardian#76]
If I visit hexdocs.pm/guardian, it redirects to http://hexdocs.pm/guardian/overview.html which is 404, which makes it a little bit harder to find the published docs. They are available at https://hexdocs.pm/guardian/Guardian.html

**Comment by hassox** [comment]
Thanks. Not sure what's going on but I'll look into it

**Comment by hassox** [comment]
This is working now :) Thanks for the heads up
