### ISSUE TITLE
Handling Errors in LoadResource

### ISSUE THREAD

**Issue by joshwlewis** [ueberauth/guardian#78]
Hi y'all,

Just came across some unexpected functionality:

``` elixir
defmodule MyApp.TokenSerializer do
  @behaviour Guardian.Serializer
  alias MyApp.Repo
  alias MyApp.User

  ...

  def from_token(id) do
    case user = Repo.get(User, id) do
      %User{} ->
        {:ok, user}
      nil ->
        {:error, "Unknown resource"}
    end
  end
end
```

My naive impression was that that returning an error here would cause Guardian to abort the request in some fashion. However, the error is swallowed up [here](https://github.com/ueberauth/guardian/blob/master/lib/guardian/plug/load_resource.ex#L29).

I'll likely implement my own plug to verify that the `current_resource` is not nil for now, but I thought it might be nice if Guardian provided something similar. Two ideas:
- Plug.LoadResource could call the `unauthenticated` method on the handler when the serializer returns an error
- A new plug like (Plug.EnsureResource?) that calls the `unauthenticated` method on the handler when the serializer returns an error

I'm happy to take a stab at a PR if you like either idea.

**Comment by hassox** [comment]
Hi @joshwlewis. Perhaps we could pass an option into load resource where when it can't find one it calls the handler? Perhaps even the presence of a handler option would tell it to call some action?

**Comment by fnimick** [comment]
+1 this would be very helpful!

**Comment by hassox** [comment]
@joshwlewis just checking in on this. Did you need some help?

**Comment by joshwlewis** [comment]
Sorry, looks like I let this slide. Let me see if I can get something together later tonight.

**Comment by hassox** [comment]
No problem @joshwlewis I was just going through issues and wanted to touch base.

**Comment by doomspork** [comment]
Howdy @joshwlewis, any updates here? 😀

**Comment by doomspork** [comment]
@hassox / @joshwlewis any updates here?  If there's no movement how about we close?

**Comment by coryodaniel** [comment]
I came across this same issue/assumption last night? Any progress? If someone isn't actively on this, I wouldn't mind working on a solution tomorrow evening. LMK :D

**Comment by doomspork** [comment]
@coryodaniel I say go for it!

**Comment by coryodaniel** [comment]
@doomspork  should load resource have its own off air handler like ensure authenticated?

Also regarding ensure authenticated ... is that the best name for the module since it's technically ensuring the token is verified?

**Comment by coryodaniel** [comment]
So I haven't created a PR, I solved it in my application first, curious how you guys see this integrated... Maybe its just another plug to be added?

```elixir
defmodule MyApp.Plug.RequireUser do
  import Plug.Conn

  def init(opts), do: opts

  def call(conn, _opts) do
    case conn.private[:guardian_default_resource] do
      nil ->
        conn
        |> MyApp.AuthErrorHandler.unauthenticated(%{})
        |> halt
      _ -> conn
    end
  end
end
```

**Comment by steffenix** [comment]
Did you guys found a way to do it?

**Comment by doomspork** [comment]
@steffenix we haven't added anything to the library to handle this, others have found their own solutions.  If you or @coryodaniel want to open a PR, we can discuss the implementation 👍

**Comment by doomspork** [comment]
This has been handled via #238
