### ISSUE TITLE
Question about using conn.assigns vs conn.private

### ISSUE THREAD

**Issue by aaronrenner** [ueberauth/guardian#80]
I'm still pretty new to Elixir/Phoenix, so please forgive me if this a noob question. Guardian looks like a great authentication library, but I have one question...

I've been looking through the codebase and see a lot of guardian's internal state is stored on `conn.assigns` instead of using `conn.private`. It looks like guardian is currently adding keys like `:guardian_default_claims` and `:guardian_default_jwt` to the assigns hash, which I think makes them available in phoenix templates by using`@guardian_default_claims` and `@guardian_default_jwt`, respectively. I was thinking that the assigns hash was only for things the developer wanted to access in their template using the `@variable_name` syntax. I'm curious about what the advantage is of putting these keys in `conn.assigns` versus storing them in `conn.private` and exposing a helper function to access them if they really need to be accessed. 

Any insight on this would be greatly appreciated as I continue to learn Phoenix.

**Comment by hassox** [comment]
I'm not sure if they're available in the template but private is a much better place for it. I wrote guardian as a noob and didn't know any better. Do you think you could put a or together? I'd totally merge a move to private

**Comment by aaronrenner** [comment]
Awesome. I'll get started on it!
