### ISSUE TITLE
Recompile on permissions update?

### ISSUE THREAD

**Issue by skosch** [ueberauth/guardian#84]
Hi,

forgive the somewhat unrelated question, but as a newcomer to Elixir, I just pulled my hair out for way too long because my permissions weren't working ... until I realized that `mix` actually compiles the Map in `config.exs` directly into the `@perms` attribute, and that said compilation isn't automatically re-triggered when my configuration changes. In other words, I have to delete `_build/guardian` after updating my permissions or else my app won't work.

If this should happen automatically, then something must be missing in my setup, and I'd be grateful for a pointer to a working example.

**Comment by hassox** [comment]
oh that's a good point. The GuardianPermissions module is dynamically generated. I'm not sure how to watch for changes in the config and re-generate. That's an interesting challenge though.

**Comment by skosch** [comment]
Hm. I guess it's not that big of a deal in practice, but maybe a note in the docs would be helpful to save the next guy a few hours :)

**Comment by hassox** [comment]
Quick update on this. I've looked into getting some code reloading happening, and while it's very possible, it still doesn't help with partial compilations like tests. Only in dev. I'm going to take a stab at refactoring the permissions module to be a more run-time set of functions rather than compile time definitions.

**Comment by skosch** [comment]
Sweet, thank you! Looking forward to what you'll come up with. I'll keep the issue open until then.

**Comment by sschneider1207** [comment]
It would be nice to have a notice about this in the section of the readme on permissions, I just had this same problem and couldn't figure out what was wrong for the life of me.
