### ISSUE TITLE
encode_and_sign without hooks?

### ISSUE THREAD

**Issue by terakilobyte** [ueberauth/guardian#85]
It would be nice from a testing perspective to be able to generate a throwaway token for testing, especially when using GuardianDB.

If I've missed this utility somewhere I apologize. If not, I'd definitely be up for submitting a PR.

**Comment by hassox** [comment]
You can apply your hooks in prod, staging and dev if you want and leave it out of test. Would that work for you?

**Comment by terakilobyte** [comment]
I think there's value in being able to use hooks in testing to create a valid user. This might be specialized purely towards guardiandb, but having access to both in testing allows a user like myself to make the assertion that all is well and the "user" must have a valid JWT issued by my application.

I don't see a way to do this, though if it's inbuilt I apologize and would ask for reference.

**Comment by hassox** [comment]
You can use a combination of setup and on_exit to remove the hooks.

```elixir
setup_all do
  hooks = Application.get_env(:guardian, :hooks)
  Application.put_env(:guardian, :hooks, nil)
  on_exit(make_ref, fn -> Application.put_env(:guardian, :hooks, hooks) end)
  {:ok, []}
end
```

I think something like that would do what you're looking for.

**Comment by terakilobyte** [comment]
Yep, that worked perfectly, thanks!
