### ISSUE TITLE
Make Generators

### ISSUE THREAD

**Issue by victorlcampos** [ueberauth/guardian#87]
Hi,
if you agree I think I can help you to make some generators like device has

**Comment by victorlcampos** [comment]
Can u make a generator for: https://hassox.github.io/elixir/guardian/2015/06/29/simple-email-password-authentication.html

**Comment by hassox** [comment]
Hey @victorlcampos I'm happy for a project that works similarly to devise. It's not really my thing right now though but please feel free to use the code you find on my blog or in example apps to get you going.

**Comment by victorlcampos** [comment]
I opened a new project called gen_guardian(https://github.com/victorlcampos/gen_guardian), in the future, when I finish, if you agree we merge both
