### ISSUE TITLE
Write guides on API and Browser Auth with Guardian/Phoenix.

### ISSUE THREAD

**Issue by nicholaswyoung** [ueberauth/guardian#91]
This issue will be closed once I write the guides. It's mostly here as a placeholder to remind myself what I need to do.

The idea is prose + code, a walkthrough that explains both how to use Guardian and why a user should consider it.

**Comment by OxySocks** [comment]
I would be really interested in this, sounds great.

**Comment by nicholaswyoung** [comment]
I have a working example, I just need to write the prose portion. Soon...

**Comment by somlor** [comment]
@nicholaswyoung let me know if you'd like any kind of help with this guide. Would be a great resource.

**Comment by nicholaswyoung** [comment]
@somlor @hassox Okay, I finally have some time to work on these, maybe during the coming weekend. Any input on how they should be structured in the repo? `docs/` / `examples/`? Or should they go in a separate `guides` repo?

**Comment by doomspork** [comment]
What do you plan to put together @nicholaswyoung?  I think that might better dictate where it lives.

@hassox already has a pretty solid example, so I'm not sure there's much need for more of those: https://github.com/hassox/phoenix_guardian

**Comment by doomspork** [comment]
@nicholaswyoung is this something you're still working on or can we close this issue?

**Comment by nicholaswyoung** [comment]
@doomspork Still on it. But you can close the issue if doing so is helpful. 

I've been busy with a new child, so I haven't had copious amounts of time to dedicate to this project, so progress is slow.

**Comment by doomspork** [comment]
No worries @nicholaswyoung, congrats on the new kid!  I just wanted to check in.

**Comment by simonh1000** [comment]
I would certainly welcome some instructions or a blog, and ideally for a json api. What I can't see at all from the docs is where the username and password are sent and matched with the database. That must be done before a token can be issued I would expect.

**Comment by hassox** [comment]
Hey @simonh1000 you can see some walkthroughs on the overstuffed gorilla blog. For example: http://blog.overstuffedgorilla.com/simple-guardian-api-authentication/

**Comment by nicholaswyoung** [comment]
This should be a blog entry first. I'll get to that shortly, but for now, I'll close the issue.
