### ISSUE TITLE
Question: How can I authenticate a user via api and session simultaneously?

### ISSUE THREAD

**Issue by JHKennedy4** [ueberauth/guardian#95]
I am trying to authenticate a user via api, but I'd also like to make sure they remain authenticated should they refresh the page.

Guardian.Plug.sign_in seems to fit the bill for storing user authentication in a cookie, but the cookie doesn't get set when I auth via my api.

This does work:
```
    conn
    |> Guardian.Plug.sign_in(user)
    |> redirect(to: root_path(conn, :index))
```
Using these pipelines in this order:

```
      pipeline :browser do
         plug :accepts, ["html"]
         plug :fetch_session
         plug :fetch_flash
         plug :protect_from_forgery
         plug :put_secure_browser_headers
       end
    
       pipeline :browser_session do
         plug Guardian.Plug.VerifySession
         plug Guardian.Plug.LoadResource
       end
```

This does not:

```
    conn
    |> Guardian.Plug.sign_in(user)
    |> render("session.json")
```
Using these pipelines in this order:
```
      pipeline :api do
         plug :accepts, ["json"]
         plug Guardian.Plug.VerifyHeader
         plug Guardian.Plug.LoadResource
      end
    
      pipeline :api_session do
         plug :fetch_session
         plug :fetch_flash
         plug :put_secure_browser_headers
         plug Guardian.Plug.VerifySession
      end
```
I'm out of guesses as to why one works and the other doesn't as the behavior of [`redirect`](https://github.com/phoenixframework/phoenix/blob/v1.1.4/lib/phoenix/controller.ex#L298) and [`render`](https://github.com/phoenixframework/phoenix/blob/v1.1.4/lib/phoenix/controller.ex#L479) seem to be essentially the same.

Is there something I'm missing?

**Comment by hassox** [comment]
Worked through this. Seems the fetch polyfil does not allow the session cookie to be sent.

**Comment by AlexKovalevych** [comment]
I guess this one is related: https://github.com/github/fetch#sending-cookies
